# Preparing Environment

In [1]:
import numpy as np
import pandas as pd
import openpyxl
import re
import umap
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 200)

In [2]:
covariates = ['sex', 'HTN', 'DM', 'CKD', 'CLD', 'Asthma', 'COPD', 'CLD (chronic lung disease)', 'Stroke', 
              'Spinal Cord Injury', 'Neuro (Parkinsons, Epilepsy, Dementia)', 'Obesity', 'Immunodeficiency ', 
              'Cancer', 'Anxiety', 'Depression', 'Psych', 'Eating disorder', 'IBD/IBS']
symptoms = ['Abnormal Body Temperature', 'Unexplained sweat/flushing', 'Difficult / Labored Breathing, SoB', 
            'Breathing faster than normal ', 'Fatigue (1)', 'Weakness', 'Postexertional Malaise (7)', 'Cough', 
            'Chronic Cough (4)', 'Dizziness (1)', 'Fainting/blackouts', 'Headache', 'Joint Pain arthralgia', 
            'Chest Pain (2)', 'Paliptations (2)', 'Brain Fog (3)', 'Confusion, difficulty thinking', 
            'Disoriented, getting lost', 'Forgetful, memory problem', 'Loss of Taste', 'Loss of Smell', 
            'Difficulty swallowing', 'Loss of Appetite/weight loss', 'Dry Mouth', 'Thirst (3)', 'Dry Eye', 
            'Rhinitis', 'Sore throat', 'Diarrhea', 'Nausea', 'Vomitting', 'Acid Reflux/indigestion', 'Bloating', 
            'Abdominal Pain', 'Muscle Pain', 'Tingling/numbness in the mouth/face', 
            'Tingling/Numbness burning, stabbing, pin and needle', 'Sleep Disturbace', 'Swelling', 
            'Urinary incontinence ', 'Menstrual irregularity ', 'Hair Loss (0)', 'Rashes/ skin lesions', 
            'tinnitus', 'Difficulty hearing', 'Vision effects/double blurry vision ', 'Fever/Chills', 'Anxiety', 
            'Mood swing/irritabiity, Depression', 'Exaggerated sx or worse from alcohol ', 
            'Sexual desire or capacity (1)', 'Abnormal Movements (1)']
other = ['RBD MENSA IgG', 'S1 MENSA IgG', 'S2 MENSA IgG', 'NP MENSA IgG', 'CMV_gB_1 MENSA IgG', 'CMV_Pentamer MENSA IgG', 
         'EBV_EBNA1 MENSA IgG', 'EBV_VCA MENSA IgG', 'EBV_gp350 MENSA IgG', 'HSV2_gD MENSA IgG', 'RBD Serum IgG', 
         'S1 Serum IgG', 'S2 Serum IgG', 'NP Serum IgG', 'CMV_gB_1 Serum IgG', 'CMV_Pentamer Serum IgG', 
         'EBV_EBNA1 Serum IgG', 'EBV_VCA Serum IgG', 'EBV_gp350 Serum IgG', 'HSV2_gD Serum IgG']

# Symptom mapping to sinai

In [3]:
data_dictionary = pd.read_csv("data_dictionary - Sheet1.csv").astype(str)
data_dictionary = data_dictionary.replace("currentsymptoms_7\r", "currentsymptoms_7")
data_dictionary = data_dictionary[data_dictionary["Sinai Name"] != "nan"]
data_dictionary = data_dictionary[data_dictionary["Emory Name"] != "nan"]
data_dictionary = dict(zip(data_dictionary["Emory Name"], data_dictionary["Sinai Name"]))
data_dictionary

{'Brain Fog (3)': 'currentsymptoms_27',
 'Confusion, difficulty thinking': 'currentsymptoms_28',
 'Forgetful, memory problem': 'currentsymptoms_30',
 'Fatigue (1)': 'currentsymptoms_15',
 'Cough': 'currentsymptoms_11',
 'Difficult / Labored Breathing, SoB': 'currentsymptoms_13',
 'Breathing faster than normal': 'currentsymptoms_14',
 'Headache': 'currentsymptoms_2',
 'Sleep Disturbace': 'currentsymptoms_42',
 'Weakness': 'currentsymptoms_31',
 'Joint Pain arthralgia': 'currentsymptoms_33',
 'Loss of Appetite/weight loss': 'currentsymptoms_24',
 'Nausea': 'currentsymptoms_21',
 'Chest Pain (2)': 'currentsymptoms_16',
 'Paliptations (2)': 'currentsymptoms_17',
 'Loss of Smell': 'currentsymptoms_8',
 'Muscle Pain': 'currentsymptoms_32',
 'Rashes/ skin lesions': 'currentsymptoms_41',
 'Dizziness (1)': 'currentsymptoms_18',
 'Tingling/Numbness burning, stabbing, pin and needle': 'currentsymptoms_35',
 'Vision effects/double blurry vision': 'currentsymptoms_5',
 'Sore throat': 'currentsymptoms_12',
 'Diarrhea': 'currentsymptoms_20',
 'Abdominal Pain': 'currentsymptoms_26',
 'Fever/Chills': 'currentsymptoms_1',
 'Abnormal Body Temperature': 'currentsymptoms_3',
 'Vomitting': 'currentsymptoms_22',
 'Fainting/blackouts': 'currentsymptoms_19',
 'Sexual desire or capacity (1)': 'currentsymptoms_39',
 'Unexplained sweat/flushing': 'currentsymptoms_4',
 'Difficulty hearing': 'currentsymptoms_6',
 'tinnitus': 'currentsymptoms_7',
 'Loss of Taste': 'currentsymptoms_9',
 'Difficulty swallowing': 'currentsymptoms_10',
 'Acid Reflux/indigestion': 'currentsymptoms_23',
 'Bloating': 'currentsymptoms_25',
 'Disoriented, getting lost': 'currentsymptoms_29',
 'Tingling/numbness in the mouth/face': 'currentsymptoms_34',
 'Swelling': 'currentsymptoms_36',
 'Urinary incontinence': 'currentsymptoms_37',
 'Menstrual irregularity': 'currentsymptoms_38',
 'Hair Loss (0)': 'currentsymptoms_40',
 'Mood swing/irritabiity, Depression': 'currentsymptoms_43',
 'Exaggerated sx or worse from alcohol': 'currentsymptoms_44'}

In [4]:
symptoms = ['Abnormal Body Temperature', 'Unexplained sweat/flushing', 'Difficult / Labored Breathing, SoB', 'Breathing faster than normal ', 'Fatigue (1)', 'Weakness', 'Postexertional Malaise (7)', 'Cough', 'Chronic Cough (4)', 'Dizziness (1)', 'Fainting/blackouts', 'Headache', 'Joint Pain arthralgia', 'Chest Pain (2)', 'Paliptations (2)', 'Brain Fog (3)', 'Confusion, difficulty thinking', 'Disoriented, getting lost', 'Forgetful, memory problem', 'Loss of Taste', 'Loss of Smell', 'Difficulty swallowing', 'Loss of Appetite/weight loss', 'Dry Mouth', 'Thirst (3)', 'Dry Eye', 'Rhinitis', 'Sore throat', 'Diarrhea', 'Nausea', 'Vomitting', 'Acid Reflux/indigestion', 'Bloating', 'Abdominal Pain', 'Muscle Pain', 'Tingling/numbness in the mouth/face', 'Tingling/Numbness burning, stabbing, pin and needle', 'Sleep Disturbace', 'Swelling', 'Urinary incontinence ', 'Menstrual irregularity ', 'Hair Loss (0)', 'Rashes/ skin lesions', 'tinnitus', 'Difficulty hearing', 'Vision effects/double blurry vision ', 'Fever/Chills', 'Anxiety', 'Mood swing/irritabiity, Depression', 'Exaggerated sx or worse from alcohol ', 'Sexual desire or capacity (1)', 'Abnormal Movements (1)']
symptoms_new = []
for s in symptoms: 
    s = s.lower().replace(" ", "_").replace("/", "_").replace(",", "_").replace("(", "_").replace(")", "_")
    while "__" in s: 
        s = s.replace("__", "_")
    if s[-1] == "_": s = s[:-1]
    symptoms_new.append(s)
symptoms_dict = dict(zip(symptoms, symptoms_new))
symptoms_dict

{'Abnormal Body Temperature': 'abnormal_body_temperature',
 'Unexplained sweat/flushing': 'unexplained_sweat_flushing',
 'Difficult / Labored Breathing, SoB': 'difficult_labored_breathing_sob',
 'Breathing faster than normal ': 'breathing_faster_than_normal',
 'Fatigue (1)': 'fatigue_1',
 'Weakness': 'weakness',
 'Postexertional Malaise (7)': 'postexertional_malaise_7',
 'Cough': 'cough',
 'Chronic Cough (4)': 'chronic_cough_4',
 'Dizziness (1)': 'dizziness_1',
 'Fainting/blackouts': 'fainting_blackouts',
 'Headache': 'headache',
 'Joint Pain arthralgia': 'joint_pain_arthralgia',
 'Chest Pain (2)': 'chest_pain_2',
 'Paliptations (2)': 'paliptations_2',
 'Brain Fog (3)': 'brain_fog_3',
 'Confusion, difficulty thinking': 'confusion_difficulty_thinking',
 'Disoriented, getting lost': 'disoriented_getting_lost',
 'Forgetful, memory problem': 'forgetful_memory_problem',
 'Loss of Taste': 'loss_of_taste',
 'Loss of Smell': 'loss_of_smell',
 'Difficulty swallowing': 'difficulty_swallowing',
 'Loss of Appetite/weight loss': 'loss_of_appetite_weight_loss',
 'Dry Mouth': 'dry_mouth',
 'Thirst (3)': 'thirst_3',
 'Dry Eye': 'dry_eye',
 'Rhinitis': 'rhinitis',
 'Sore throat': 'sore_throat',
 'Diarrhea': 'diarrhea',
 'Nausea': 'nausea',
 'Vomitting': 'vomitting',
 'Acid Reflux/indigestion': 'acid_reflux_indigestion',
 'Bloating': 'bloating',
 'Abdominal Pain': 'abdominal_pain',
 'Muscle Pain': 'muscle_pain',
 'Tingling/numbness in the mouth/face': 'tingling_numbness_in_the_mouth_face',
 'Tingling/Numbness burning, stabbing, pin and needle': 'tingling_numbness_burning_stabbing_pin_and_needle',
 'Sleep Disturbace': 'sleep_disturbace',
 'Swelling': 'swelling',
 'Urinary incontinence ': 'urinary_incontinence',
 'Menstrual irregularity ': 'menstrual_irregularity',
 'Hair Loss (0)': 'hair_loss_0',
 'Rashes/ skin lesions': 'rashes_skin_lesions',
 'tinnitus': 'tinnitus',
 'Difficulty hearing': 'difficulty_hearing',
 'Vision effects/double blurry vision ': 'vision_effects_double_blurry_vision',
 'Fever/Chills': 'fever_chills',
 'Anxiety': 'anxiety',
 'Mood swing/irritabiity, Depression': 'mood_swing_irritabiity_depression',
 'Exaggerated sx or worse from alcohol ': 'exaggerated_sx_or_worse_from_alcohol',
 'Sexual desire or capacity (1)': 'sexual_desire_or_capacity_1',
 'Abnormal Movements (1)': 'abnormal_movements_1'}

# Loading Data

In [5]:
file = "data_from_collaborators/Data Collection for Sinai_v2.xlsx"
file = openpyxl.load_workbook(file, data_only = True)
print(file.sheetnames)

['Sheet1']

In [6]:
# Getting raw data
sheet = "Sheet1"
data = pd.DataFrame(file[sheet].values).astype(str)
data = data.fillna(float("nan"))
data.columns = [str(val) for val in data.iloc[0,:]]
data = data.iloc[1:, :]
data = data[data["Subject #"] != "3477"].reset_index(drop = True)
keep = [0, 2]
keep.extend(range(10, 28))
keep.extend(range(38, 90))
first = 0
last = 0
igg_cols = []
for i in range(data.shape[1]): 
    col = list(data.columns)[i]
    if "serum" in col.lower() or "mensa" in col.lower(): 
#         print(col)
        data = data.rename(columns = {col: col.lower().replace(" ", "_")})
        col = col.lower().replace(" ", "_")
        igg_cols.append(col)
        if first == 0: 
            first = i
        last = i
keep.extend(range(first, last + 1))
data = data.iloc[:,keep]
data = data.rename(columns = {"Gender ": "sex", "Exaggerated sx or worse from alcohol ":"Exaggerated sx or worse from alcohol"})
data = data.rename(columns = data_dictionary)
data = data.replace("3579 3582", 3582)
data.index = data["Subject #"]
print(data.shape)
data

(60, 92)

,Subject #,sex,HTN,DM,CKD,CLD,Asthma,COPD,CLD (chronic lung disease),Stroke,Spinal Cord Injury,"Neuro (Parkinsons, Epilepsy, Dementia)",Obesity,Immunodeficiency,Cancer,Anxiety,Depression,Psych,Eating disorder,IBD/IBS,currentsymptoms_3,currentsymptoms_4,currentsymptoms_13,Breathing faster than normal,currentsymptoms_15,currentsymptoms_31,Postexertional Malaise (7),currentsymptoms_11,Chronic Cough (4),currentsymptoms_18,currentsymptoms_19,currentsymptoms_2,currentsymptoms_33,currentsymptoms_16,currentsymptoms_17,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_9,currentsymptoms_8,currentsymptoms_10,currentsymptoms_24,Dry Mouth,Thirst (3),Dry Eye,Rhinitis,currentsymptoms_12,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_25,currentsymptoms_26,currentsymptoms_32,currentsymptoms_34,currentsymptoms_35,currentsymptoms_42,currentsymptoms_36,Urinary incontinence,Menstrual irregularity,currentsymptoms_40,currentsymptoms_41,currentsymptoms_7,currentsymptoms_6,Vision effects/double blurry vision,currentsymptoms_1,Anxiety_2,currentsymptoms_43,currentsymptoms_44,currentsymptoms_39,Abnormal Movements (1),rbd_mensa_igg,s1_mensa_igg,s2_mensa_igg,np_mensa_igg,cmv_gb_1_mensa_igg,cmv_pentamer_mensa_igg,ebv_ebna1_mensa_igg,ebv_vca_mensa_igg,ebv_gp350_mensa_igg,hsv2_gd_mensa_igg,rbd_serum_igg,s1_serum_igg,s2_serum_igg,np_serum_igg,cmv_gb_1_serum_igg,cmv_pentamer_serum_igg,ebv_ebna1_serum_igg,ebv_vca_serum_igg,ebv_gp350_serum_igg,hsv2_gd_serum_igg
Subject #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3633,3633,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,1,0,0,0,1,1,0,0,1,61.25,84.5,59,11.75,25.5,1,7.25,39.25,0.75,-8.5,197923,181317,187498.5,27079.25,295,252.75,74592.5,2029,213.5,57061.75
7191,7191,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,186,118.5,193.25,27,127.5,48.75,112.5,81.5,37,92.5,137940.75,112925,154675,43216.5,80568.75,32537.5,6770.5,46710,19973.75,90179.75
7283,7283,M,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,593.5,426.25,376.25,-9.75,163,132.5,66.75,21.5,14.5,-22.75,215546,211708,227075.5,547.25,114837.75,54140,92600.75,12822.75,352.75,399.25
7385,7385,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,1,0,0,0,1,0,1,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,1,0,0,0,1,1,0,0,0,0,0,223.25,190.25,235,17,197.75,87,130,493.5,156.5,51.25,182501,166949.25,188780,3507.5,113108.5,61596.25,127289.5,186401.5,114430.25,83217.5
7415,7415,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,1,0,1,1,0,1,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1113,685.25,665.75,22.75,17.5,7,20,90.75,105.5,11,180698,199563,229105.25,1575,476.5,367.5,25938,32915,45131.25,209.75
7423,7423,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,258.5,166.5,282.5,-1,36,22.25,10.25,270,52.5,207,174829.75,144314.25,205137.75,562,257.25,134.5,68627.5,108870,64012.25,128146.5
7424,7424,F,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1,0,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0,0,1893.5,1323.25,2509.75,-5,115.5,100.25,-11.25,637,1649.5,283.5,174166,201581.5,206533,15292.75,66127,48691.5,6081,157824.75,197410.5,127998.75
7426,7426,M,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,1,1,1,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,956.75,640.25,393.75,45.25,90.25,124.25,-10,64.25,-21.5,43.75,189378.75,191103,187612,33458.5,54611.25,73298.75,50223,18252,7954.25,58212.75
7010,7010,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,201.75,112.5,176.25,-18.25,-32.75,37.5,1126.25,2836.25,65.5,58.25,53927.75,33040.25,51370.75,1669,77.75,202.5,223942.75,182973.5,19613.5,16821
7023,7023,M,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1047,768,833.5,3.25,81.25,85.5,6,192.75,234,34.25,193681.25,209817.5,247009.25,51569.25,133783.25,95077.25,212439,207342.75,170871,124249
7024,7024,F,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,217.75,73.25,32.75,-35,-15,40.75,-19.75,15,108.5,-12,210568,182090.5,91940.25,104.5,23952,8869.5,102165.5,77164.25,152883,135.75
7030,7030,M,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,1,1,1,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1416.25,966.5,620.25,155.75,-24.25,56.25,-7,589.25,1967,-11.75,194634.25,213084.75,235449,134422.25,108.5,132.25,22784.25,187744,245384.75,150.25
7033,7033,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,125.5,84.25,76.5,-10.75,52.25,46.75,184,13,2.75,64.75,89721,71318,69896.75,451.75,55780.5,36485.75,219376.25,16728.75,5152.75,101877
7034,7034,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,1,1,0,0,0,1,0,1,1,1,1,0,0,1,1,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1475.25,896.5,245.5,155.5,-33.75,60.25,107.75,527.5,140.75,5.5,191514,226807,198293.75,157220,80.75,634,199925,185866.75,81829.5,33432
7032,7032,F,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,1,1,0,0,1,0,1,0,1,1,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,0,1,1,0,0,0,0,0,0,815.75,567,579,3,151.5,327.25,10,373,110.25,16.75,222582.25,186373.25,198345,24216.75,113532.75,80674.75,35615.75,56992.75,24934.5,117.5
7053,7053,F,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,985,989,3112.25,50,-18.25,38.5,1236.5,3190,6949,17.75,194219.75,196038.75,240821,14998.25,186.5,305.75,218797.75,167260.5,205853.5,236.25
7069,7069,F,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,1,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,0,0,1,526.75,407.75,459,-22,-24.25,71.25,82,738.5,453.25,547.25,187866.75,165923.75,182536,327.25,78.25,161.25,95925.75,179473.75,133829.5,149741.25
7075,7075,F,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,195,99.75,251.5,55.25,56,54.25,26.5,71,228.25,71.5,195303.5,157148.5,213394.5,83523,63041.5,62256,136019.25,72490,193180.75,100532.5
7076,7076,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1027.25,593.75,439.25,17.75,-21.25,48,276.5,137.75,44.5,95.25,236139.75,203231.75,193211.25,7349.75,71.5,233,192397.75,124773.5,19715.75,73020.75
7077,7077,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19861.75,14175.25,8152,239.5,632.75,1117.5,260,808,336.25,1255.25,202796.75,238566,269013,20995.25,71204.5,111107.25,53013.25,95861,41436,123636.5
7090,7090,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,48.25,6.5,47.75,-18.5,-9.5,30.5,34.25,56.25,236.5,37.25,18366.75,12916.25,45414.5,843.75,24.75,309,74029.75,68933.75,94229.75,68046.25
3198,3198,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,156,71.25,184.75,94,16.25,199,38.75,827.5,245.25,88.25,160099.75,107969.75,165360.25,91536,55439.75,123372.5,90201.75,156743.5,137507.75,114457.75
3199,3199,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,152.75,104.25,173.5,163,139.25,498.5,92.75,192.75,343.25,145.75,133586.75,79011.5,96320,113761,123061.75,181453,122251.5,115294.25,184101.75,119750.5
3231,3231,F,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,163,142,540.5,71,198,261,590.25,177.25,145,136.25,116688.25,78382,132947.75,49724,154203.75,171685,115898.5,150849.5,70362.5,97287
3232,3232,F,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,77,28.75,33.5,180,192.25,47.75,98.5,280.75,86.75,384.75,82,540.5,257.5,119283.75,83761.25,59088.5,55818.25,154151,78965
3234,3234,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1049,666,2179.75,294.5,327.5,429.25,1107,133.5,124.25,130.25,189370,186347,213520,118185.5,125529.25,152546,159865.75,76959.5,99847.75,90276
3260,3260,M,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,257.5,155.25,415.5,255.25,83.5,367.5,186.75,95.75,91.25,90.25,52605.75,27137,68865.5,94536.75,36669.5,114648,18603.75,75694.25,82172.75,44782.5
3264,3264,F,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,935.25,484.75,2035.75,94,66.25,284,69.75,129.25,625.75,57.5,189438,136156.75,206270.5,78404.5,52268.75,70850.5,52673,81026.75,141926.75,66054.25
3290,3290,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,1,0,0,1,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,94.25,59.5,1250,67.25,53,46,43.25,284.25,504.5,62.5,3486.75,1625.5,104987.75,407.25,65.25,183,3850.75,22469.5,39004.5,126
3292,3292,F,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,397,270.25,962.5,176,278.75,553.5,543.5,4591.5,552.75,3685.25,28118,16859.5,52829.25,6405.5,24502,43367.25,73615.5,155818.5,43389.5,139235.25
3299,3299,F,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,902.75,534,884.25,755.5,184.25,777,29.25,59.25,44,199,192784.75,164263.75,212850.25,154614.25,100406,171900.5,29302.25,48625.25,2987,106544.5
3320,3320,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1713.75,1132.5,485.25,2328.5,644,1482.5,265.75,783,2884.5,222,131839.5,96653.5,61990.25,141618.75,75492.25,109542.75,63762.5,116054.25,184010.75,33131
3322,3322,M,1,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1703.75,921.5,11201.25,1505.25,28.5,47,604.5,1584.5,1238.75,486.75,154030.25,99126.5,220083,126364.75,74.75,220.5,92663.75,138767.25,95991,50602
3323,3323,F,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1172.25,435.25,1055.25,186.25,311,299.75,184,260.25,301.25,245.5,174303.5,110687.5,168968.25,48504.25,85379.5,79575,101337,61349,88145.75,83502.75
3324,3324,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,205.5,139.5,828,62.25,747,481,163.5,1048.5,1124.75,694.25,29042.5,8420.5,106150.75,11227.25,140056.5,98418.75,70178,173119.75,149510.75,127266.25
3339,3339,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2327.5,1217.5,2915.25,359,786.25,984.75,1652.75,961.75,846.25,500.25,42543,22916.5,83789.75,53416.75,118773.5,145619.75,36279.25,171429.25,150600,113612.5
3341,3341,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4118.25,2824.25,4514.75,266.75,643,950.5,705.5,408.5,601.25,764.75,28486.25,13434,71599.25,62651.75,81125,87085.5,65016,38125.75,62006.75,109778
3346,3346,F,1,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,322.5,249,630.5,53.5,258.25,339.75,36.25,26.75,50.75,82.75,129343.75,80787.5,211443.5,65057,176434.5,167895.5,635.25,190.5,74.75,108.5
3362,3362,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,123.75,98.25,333.25,50.75,19.75,-21,15.25,189.25,115,88,116285.5,75943,206502.75,40823.75,36,219.75,61198.25,135511.25,84225.75,84796.5
3365,3365,F,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,67.25,64,195.5,42.25,192.25,495.5,321.25,197.25,11,162.5,35396.5,23123.25,109559,4637.5,100263.25,108335,126723.75,93123.25,1859.25,90404.25
3381,3381,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1744.5,1338.5,2333,242.75,8.25,43.75,302.5,184.25,313.5,15.5,62487.5,40178.5,128598.75,17942.5,117488.75,110795.75,76884.25,72785,68638,136637.5
3386,3386,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,159.25,98,236.25,21,-23,18.25,102.5,38.75,62.5,126.75,8619.5,4262,10107,2888.75,167.25,320,141567.75,89777.75,41388.25,130774.75
3391,3391,F,0,1,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,2232.25,1480.5,5355.5,333.75,364,777.25,640.75,549.75,333.75,762.75,120259,85601,199734.5,75635,126.25,190.5,130148,52106.5,1405.75,48900.25
3400,3400,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35,-4.25,74.75,9.5,5.5,22.75,149.75,54,92.5,-10.25,34301.5,18230,91171.25,5333.75,88.75,656.5,116370.25,78160.25,69868.5,245
3401,3401,F,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22.25,34,77.25,26.25,28.5,99.25,62.5,245.25,234.5,42,42653.5,32694.25,75011.75,7132.25,64707,26211,75262.5,149438,127294.25,70003.75
3404,3404,F,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,89.5,56.5,145.25,55.5,9,-7,51.5,184.25,99.5,10.75,28745,18876.5,62798.5,35519.25,120828.25,93548,110433.75,94926.5,82881.25,3930.5
3427,3427,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,135.25,85,280.5,18,255,1311.5,39.5,92,52.75,1,147871.75,82947.5,196497.25,23175.5,131601.5,196282.25,103385.5,85933.75,58069,158.25
3438,3438,M,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,792.75,554.75,1564.5,10.25,43,138.75,154.5,32,261.75,98.75,166384.5,130882,149708.25,80187.75,35784,21164.5,88320.75,52044.25,70367.25,96811.75
3459,3459,F,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,-12.75,-4.75,24.5,-12.5,53.25,77.5,28.75,18,22.75,35,7876.5,8056,23335.25,2830.25,108337.5,85071.5,93826,127659.5,61743.25,103167.5
3460,3460,M,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,92.5,22.75,64,11.75,95.5,179.25,910.5,150.75,314,107.5,70391.25,25811,40673.75,13387.5,46716,28620.5,136487,55973.5,94283.5,46972.25
3471,3471,M,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79,61.5,148,97.25,-8.75,0.5,163,-34.5,13,40,87968.5,56701,58296.5,85466.5,95,883.75,120276.25,7171,10126.25,47765.75
3474,3474,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,206.25,133.75,630,98.5,24,46.75,1159.75,26.25,41.5,203.25,82298.25,60154,180910.25,68814,16576.25,13246.25,161775.25,21034.75,24299,105486.75
3475,3475,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,101,62.5,47.75,9.5,33.5,126.75,30.5,20.5,34,51.75,41740.75,18502.25,70044.5,13146.75,65614,47762.75,83818.25,72836,28165.75,72419.25
3503,3503,M,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,199.25,125.75,354.5,82,727,414.25,139.75,66,105.75,109.25,75647.5,47629,94516.5,37940.5,110333.5,102381.75,94092.75,28678,35701.25,47221.75
3532,3532,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,348,257.25,721.75,8.5,165.5,181.25,186.5,303,158,210,186853.5,164726.25,216375.75,6952.5,122881.25,37392,93650.25,129479.5,17048.25,110266.5
3556,3556,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,21,14,35.75,-14.5,128.75,260.5,248.5,383.5,0.75,8,13681.25,4201.25,16396,2805,111138.5,58484.75,120214,53314,995.25,308.25
3582,3582,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,1,0,1,1,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,177.25,136.75,323,-3.5,-12,9.25,-0.5,-19.25,27,47.75,183541.5,141921.25,198390.75,1621.25,103,156.5,44503,23156,20233.5,46331.75
3580,3580,F,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,8.25,13.25,38.75,3.25,79.5,160.5,9.5,234.75,240.5,118.75,8153,4811.25,38304.25,11596.75,61753,58008.5,63939.75,108580,96489.25,81423.5
3591,3591,F,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,1,1,0,1,1,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1025.25,660,2340.5,128,238,389.5,1229.75,312,226.5,433.5,65804,43098.75,56725.5,48180.5,109057.75,69093,115956.5,49050.25,11159,127044.25
3593,3593,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,1,0,1,0,1,1,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,74.25,28.5,389.5,10,106.75,126.75,73.75,91.75,216.75,73,21439,12717.25,58761,8796.75,95656.25,50988,68021,35693,64579.75,69569.25

In [7]:
columns = list(filter(re.compile("currentsymptoms_.*").match, data.columns))
columns = [int(val.split("_")[-1]) for val in columns]
columns = sorted(columns)
columns = [f"currentsymptoms_{i}" for i in columns]
columns_ = covariates[:]
columns_.extend(columns)
columns = columns_[:]
columns.extend(igg_cols)
data = data[columns]
data

,sex,HTN,DM,CKD,CLD,Asthma,COPD,CLD (chronic lung disease),Stroke,Spinal Cord Injury,"Neuro (Parkinsons, Epilepsy, Dementia)",Obesity,Immunodeficiency,Cancer,Anxiety,Depression,Psych,Eating disorder,IBD/IBS,currentsymptoms_1,currentsymptoms_2,currentsymptoms_3,currentsymptoms_4,currentsymptoms_6,currentsymptoms_7,currentsymptoms_8,currentsymptoms_9,currentsymptoms_10,currentsymptoms_11,currentsymptoms_12,currentsymptoms_13,currentsymptoms_15,currentsymptoms_16,currentsymptoms_17,currentsymptoms_18,currentsymptoms_19,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_24,currentsymptoms_25,currentsymptoms_26,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_31,currentsymptoms_32,currentsymptoms_33,currentsymptoms_34,currentsymptoms_35,currentsymptoms_36,currentsymptoms_39,currentsymptoms_40,currentsymptoms_41,currentsymptoms_42,currentsymptoms_43,currentsymptoms_44,rbd_mensa_igg,s1_mensa_igg,s2_mensa_igg,np_mensa_igg,cmv_gb_1_mensa_igg,cmv_pentamer_mensa_igg,ebv_ebna1_mensa_igg,ebv_vca_mensa_igg,ebv_gp350_mensa_igg,hsv2_gd_mensa_igg,rbd_serum_igg,s1_serum_igg,s2_serum_igg,np_serum_igg,cmv_gb_1_serum_igg,cmv_pentamer_serum_igg,ebv_ebna1_serum_igg,ebv_vca_serum_igg,ebv_gp350_serum_igg,hsv2_gd_serum_igg
Subject #,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3633,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,61.25,84.5,59,11.75,25.5,1,7.25,39.25,0.75,-8.5,197923,181317,187498.5,27079.25,295,252.75,74592.5,2029,213.5,57061.75
7191,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,186,118.5,193.25,27,127.5,48.75,112.5,81.5,37,92.5,137940.75,112925,154675,43216.5,80568.75,32537.5,6770.5,46710,19973.75,90179.75
7283,M,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,1,0,1,1,1,1,0,0,0,0,1,0,1,1,0,593.5,426.25,376.25,-9.75,163,132.5,66.75,21.5,14.5,-22.75,215546,211708,227075.5,547.25,114837.75,54140,92600.75,12822.75,352.75,399.25
7385,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,223.25,190.25,235,17,197.75,87,130,493.5,156.5,51.25,182501,166949.25,188780,3507.5,113108.5,61596.25,127289.5,186401.5,114430.25,83217.5
7415,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,1113,685.25,665.75,22.75,17.5,7,20,90.75,105.5,11,180698,199563,229105.25,1575,476.5,367.5,25938,32915,45131.25,209.75
7423,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,258.5,166.5,282.5,-1,36,22.25,10.25,270,52.5,207,174829.75,144314.25,205137.75,562,257.25,134.5,68627.5,108870,64012.25,128146.5
7424,F,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,1,0,1,1,0,1893.5,1323.25,2509.75,-5,115.5,100.25,-11.25,637,1649.5,283.5,174166,201581.5,206533,15292.75,66127,48691.5,6081,157824.75,197410.5,127998.75
7426,M,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,0,0,1,0,0,956.75,640.25,393.75,45.25,90.25,124.25,-10,64.25,-21.5,43.75,189378.75,191103,187612,33458.5,54611.25,73298.75,50223,18252,7954.25,58212.75
7010,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,0,0,0,1,1,0,201.75,112.5,176.25,-18.25,-32.75,37.5,1126.25,2836.25,65.5,58.25,53927.75,33040.25,51370.75,1669,77.75,202.5,223942.75,182973.5,19613.5,16821
7023,M,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1047,768,833.5,3.25,81.25,85.5,6,192.75,234,34.25,193681.25,209817.5,247009.25,51569.25,133783.25,95077.25,212439,207342.75,170871,124249
7024,F,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,217.75,73.25,32.75,-35,-15,40.75,-19.75,15,108.5,-12,210568,182090.5,91940.25,104.5,23952,8869.5,102165.5,77164.25,152883,135.75
7030,M,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,1416.25,966.5,620.25,155.75,-24.25,56.25,-7,589.25,1967,-11.75,194634.25,213084.75,235449,134422.25,108.5,132.25,22784.25,187744,245384.75,150.25
7033,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,125.5,84.25,76.5,-10.75,52.25,46.75,184,13,2.75,64.75,89721,71318,69896.75,451.75,55780.5,36485.75,219376.25,16728.75,5152.75,101877
7034,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,0,1,0,1,1,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1475.25,896.5,245.5,155.5,-33.75,60.25,107.75,527.5,140.75,5.5,191514,226807,198293.75,157220,80.75,634,199925,185866.75,81829.5,33432
7032,F,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,815.75,567,579,3,151.5,327.25,10,373,110.25,16.75,222582.25,186373.25,198345,24216.75,113532.75,80674.75,35615.75,56992.75,24934.5,117.5
7053,F,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,985,989,3112.25,50,-18.25,38.5,1236.5,3190,6949,17.75,194219.75,196038.75,240821,14998.25,186.5,305.75,218797.75,167260.5,205853.5,236.25
7069,F,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,1,0,0,0,1,1,1,0,1,1,1,1,0,1,0,0,0,1,1,1,0,526.75,407.75,459,-22,-24.25,71.25,82,738.5,453.25,547.25,187866.75,165923.75,182536,327.25,78.25,161.25,95925.75,179473.75,133829.5,149741.25
7075,F,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,195,99.75,251.5,55.25,56,54.25,26.5,71,228.25,71.5,195303.5,157148.5,213394.5,83523,63041.5,62256,136019.25,72490,193180.75,100532.5
7076,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1027.25,593.75,439.25,17.75,-21.25,48,276.5,137.75,44.5,95.25,236139.75,203231.75,193211.25,7349.75,71.5,233,192397.75,124773.5,19715.75,73020.75
7077,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,19861.75,14175.25,8152,239.5,632.75,1117.5,260,808,336.25,1255.25,202796.75,238566,269013,20995.25,71204.5,111107.25,53013.25,95861,41436,123636.5
7090,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,48.25,6.5,47.75,-18.5,-9.5,30.5,34.25,56.25,236.5,37.25,18366.75,12916.25,45414.5,843.75,24.75,309,74029.75,68933.75,94229.75,68046.25
3198,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,156,71.25,184.75,94,16.25,199,38.75,827.5,245.25,88.25,160099.75,107969.75,165360.25,91536,55439.75,123372.5,90201.75,156743.5,137507.75,114457.75
3199,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,152.75,104.25,173.5,163,139.25,498.5,92.75,192.75,343.25,145.75,133586.75,79011.5,96320,113761,123061.75,181453,122251.5,115294.25,184101.75,119750.5
3231,F,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,163,142,540.5,71,198,261,590.25,177.25,145,136.25,116688.25,78382,132947.75,49724,154203.75,171685,115898.5,150849.5,70362.5,97287
3232,F,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,77,28.75,33.5,180,192.25,47.75,98.5,280.75,86.75,384.75,82,540.5,257.5,119283.75,83761.25,59088.5,55818.25,154151,78965
3234,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1049,666,2179.75,294.5,327.5,429.25,1107,133.5,124.25,130.25,189370,186347,213520,118185.5,125529.25,152546,159865.75,76959.5,99847.75,90276
3260,M,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,257.5,155.25,415.5,255.25,83.5,367.5,186.75,95.75,91.25,90.25,52605.75,27137,68865.5,94536.75,36669.5,114648,18603.75,75694.25,82172.75,44782.5
3264,F,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,935.25,484.75,2035.75,94,66.25,284,69.75,129.25,625.75,57.5,189438,136156.75,206270.5,78404.5,52268.75,70850.5,52673,81026.75,141926.75,66054.25
3290,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,94.25,59.5,1250,67.25,53,46,43.25,284.25,504.5,62.5,3486.75,1625.5,104987.75,407.25,65.25,183,3850.75,22469.5,39004.5,126
3292,F,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,397,270.25,962.5,176,278.75,553.5,543.5,4591.5,552.75,3685.25,28118,16859.5,52829.25,6405.5,24502,43367.25,73615.5,155818.5,43389.5,139235.25
3299,F,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,902.75,534,884.25,755.5,184.25,777,29.25,59.25,44,199,192784.75,164263.75,212850.25,154614.25,100406,171900.5,29302.25,48625.25,2987,106544.5
3320,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1713.75,1132.5,485.25,2328.5,644,1482.5,265.75,783,2884.5,222,131839.5,96653.5,61990.25,141618.75,75492.25,109542.75,63762.5,116054.25,184010.75,33131
3322,M,1,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1703.75,921.5,11201.25,1505.25,28.5,47,604.5,1584.5,1238.75,486.75,154030.25,99126.5,220083,126364.75,74.75,220.5,92663.75,138767.25,95991,50602
3323,F,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1172.25,435.25,1055.25,186.25,311,299.75,184,260.25,301.25,245.5,174303.5,110687.5,168968.25,48504.25,85379.5,79575,101337,61349,88145.75,83502.75
3324,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,205.5,139.5,828,62.25,747,481,163.5,1048.5,1124.75,694.25,29042.5,8420.5,106150.75,11227.25,140056.5,98418.75,70178,173119.75,149510.75,127266.25
3339,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,2327.5,1217.5,2915.25,359,786.25,984.75,1652.75,961.75,846.25,500.25,42543,22916.5,83789.75,53416.75,118773.5,145619.75,36279.25,171429.25,150600,113612.5
3341,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4118.25,2824.25,4514.75,266.75,643,950.5,705.5,408.5,601.25,764.75,28486.25,13434,71599.25,62651.75,81125,87085.5,65016,38125.75,62006.75,109778
3346,F,1,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,322.5,249,630.5,53.5,258.25,339.75,36.25,26.75,50.75,82.75,129343.75,80787.5,211443.5,65057,176434.5,167895.5,635.25,190.5,74.75,108.5
3362,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,123.75,98.25,333.25,50.75,19.75,-21,15.25,189.25,115,88,116285.5,75943,206502.75,40823.75,36,219.75,61198.25,135511.25,84225.75,84796.5
3365,F,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,67.25,64,195.5,42.25,192.25,495.5,321.25,197.25,11,162.5,35396.5,23123.25,109559,4637.5,100263.25,108335,126723.75,93123.25,1859.25,90404.25
3381,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1744.5,1338.5,2333,242.75,8.25,43.75,302.5,184.25,313.5,15.5,62487.5,40178.5,128598.75,17942.5,117488.75,110795.75,76884.25,72785,68638,136637.5
3386,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,159.25,98,236.25,21,-23,18.25,102.5,38.75,62.5,126.75,8619.5,4262,10107,2888.75,167.25,320,141567.75,89777.75,41388.25,130774.75
3391,F,0,1,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2232.25,1480.5,5355.5,333.75,364,777.25,640.75,549.75,333.75,762.75,120259,85601,199734.5,75635,126.25,190.5,130148,52106.5,1405.75,48900.25
3400,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,35,-4.25,74.75,9.5,5.5,22.75,149.75,54,92.5,-10.25,34301.5,18230,91171.25,5333.75,88.75,656.5,116370.25,78160.25,69868.5,245
3401,F,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,22.25,34,77.25,26.25,28.5,99.25,62.5,245.25,234.5,42,42653.5,32694.25,75011.75,7132.25,64707,26211,75262.5,149438,127294.25,70003.75
3404,F,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,89.5,56.5,145.25,55.5,9,-7,51.5,184.25,99.5,10.75,28745,18876.5,62798.5,35519.25,120828.25,93548,110433.75,94926.5,82881.25,3930.5
3427,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,0,1,0,0,0,1,0,0,135.25,85,280.5,18,255,1311.5,39.5,92,52.75,1,147871.75,82947.5,196497.25,23175.5,131601.5,196282.25,103385.5,85933.75,58069,158.25
3438,M,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,792.75,554.75,1564.5,10.25,43,138.75,154.5,32,261.75,98.75,166384.5,130882,149708.25,80187.75,35784,21164.5,88320.75,52044.25,70367.25,96811.75
3459,F,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,-12.75,-4.75,24.5,-12.5,53.25,77.5,28.75,18,22.75,35,7876.5,8056,23335.25,2830.25,108337.5,85071.5,93826,127659.5,61743.25,103167.5
3460,M,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,92.5,22.75,64,11.75,95.5,179.25,910.5,150.75,314,107.5,70391.25,25811,40673.75,13387.5,46716,28620.5,136487,55973.5,94283.5,46972.25
3471,M,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79,61.5,148,97.25,-8.75,0.5,163,-34.5,13,40,87968.5,56701,58296.5,85466.5,95,883.75,120276.25,7171,10126.25,47765.75
3474,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,206.25,133.75,630,98.5,24,46.75,1159.75,26.25,41.5,203.25,82298.25,60154,180910.25,68814,16576.25,13246.25,161775.25,21034.75,24299,105486.75
3475,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,101,62.5,47.75,9.5,33.5,126.75,30.5,20.5,34,51.75,41740.75,18502.25,70044.5,13146.75,65614,47762.75,83818.25,72836,28165.75,72419.25
3503,M,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,199.25,125.75,354.5,82,727,414.25,139.75,66,105.75,109.25,75647.5,47629,94516.5,37940.5,110333.5,102381.75,94092.75,28678,35701.25,47221.75
3532,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,348,257.25,721.75,8.5,165.5,181.25,186.5,303,158,210,186853.5,164726.25,216375.75,6952.5,122881.25,37392,93650.25,129479.5,17048.25,110266.5
3556,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,14,35.75,-14.5,128.75,260.5,248.5,383.5,0.75,8,13681.25,4201.25,16396,2805,111138.5,58484.75,120214,53314,995.25,308.25
3582,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,177.25,136.75,323,-3.5,-12,9.25,-0.5,-19.25,27,47.75,183541.5,141921.25,198390.75,1621.25,103,156.5,44503,23156,20233.5,46331.75
3580,F,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,8.25,13.25,38.75,3.25,79.5,160.5,9.5,234.75,240.5,118.75,8153,4811.25,38304.25,11596.75,61753,58008.5,63939.75,108580,96489.25,81423.5
3591,F,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1025.25,660,2340.5,128,238,389.5,1229.75,312,226.5,433.5,65804,43098.75,56725.5,48180.5,109057.75,69093,115956.5,49050.25,11159,127044.25
3593,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,74.25,28.5,389.5,10,106.75,126.75,73.75,91.75,216.75,73,21439,12717.25,58761,8796.75,95656.25,50988,68021,35693,64579.75,69569.25

In [8]:
# data.to_csv("data_cleaned/data_collection_for_sinai.csv", index = True)

In [9]:
comorbs = ['HTN', 'DM', 'CKD', 'CLD', 'Asthma', 'COPD', 'CLD (chronic lung disease)', 'Stroke', 'Spinal Cord Injury', 'Neuro (Parkinsons, Epilepsy, Dementia)', 'Obesity', 'Immunodeficiency ', 'Cancer', 'Anxiety', 'Depression', 'Psych', 'Eating disorder', 'IBD/IBS']
comorb = ["Hypertension", "Diabetes", "Chronic Kidney Disease", "Chronic Liver Disease (i.e Cirrhosis, Hepatitis B)", "Asthma", "Chronic Obstructive Pulmonary Disease", "Other Chronic Lung Disease", "Stroke", "Spinal Cord Injury", "Other Neurological Disease (Parkinson, Epilepsy, Dementia)", "Obesity", "Immunodeficiency (i.e auto-immune disease)", "Cancer", "Anxiety", "Depression", "Other Psychiatric Disease", "Eating disorder", "Inflammatory Bowel Disease/ Irritable Bowel Syndrome", "Other - please specify below", "None"]
comorb_dict = dict(zip(comorbs, comorb))
data = data.rename(columns = comorb_dict)
comorb_dict = dict(zip(comorb, ["comorb_selfreport_" + str(i) for i in range(1, len(comorb) + 1)]))
data = data.rename(columns = comorb_dict)
# comorb_dict = dict(zip(["comorb_selfreport_" + str(i) for i in range(1, len(comorb) + 1)], comorb))
data = data.reset_index().rename(columns = {"Subject #": "record_id"})
data

,record_id,sex,comorb_selfreport_1,comorb_selfreport_2,comorb_selfreport_3,comorb_selfreport_4,comorb_selfreport_5,comorb_selfreport_6,comorb_selfreport_7,comorb_selfreport_8,comorb_selfreport_9,comorb_selfreport_10,comorb_selfreport_11,comorb_selfreport_12,comorb_selfreport_13,comorb_selfreport_14,comorb_selfreport_15,comorb_selfreport_16,comorb_selfreport_17,comorb_selfreport_18,currentsymptoms_1,currentsymptoms_2,currentsymptoms_3,currentsymptoms_4,currentsymptoms_6,currentsymptoms_7,currentsymptoms_8,currentsymptoms_9,currentsymptoms_10,currentsymptoms_11,currentsymptoms_12,currentsymptoms_13,currentsymptoms_15,currentsymptoms_16,currentsymptoms_17,currentsymptoms_18,currentsymptoms_19,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_24,currentsymptoms_25,currentsymptoms_26,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_31,currentsymptoms_32,currentsymptoms_33,currentsymptoms_34,currentsymptoms_35,currentsymptoms_36,currentsymptoms_39,currentsymptoms_40,currentsymptoms_41,currentsymptoms_42,currentsymptoms_43,currentsymptoms_44,rbd_mensa_igg,s1_mensa_igg,s2_mensa_igg,np_mensa_igg,cmv_gb_1_mensa_igg,cmv_pentamer_mensa_igg,ebv_ebna1_mensa_igg,ebv_vca_mensa_igg,ebv_gp350_mensa_igg,hsv2_gd_mensa_igg,rbd_serum_igg,s1_serum_igg,s2_serum_igg,np_serum_igg,cmv_gb_1_serum_igg,cmv_pentamer_serum_igg,ebv_ebna1_serum_igg,ebv_vca_serum_igg,ebv_gp350_serum_igg,hsv2_gd_serum_igg
0,3633,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,61.25,84.5,59,11.75,25.5,1,7.25,39.25,0.75,-8.5,197923,181317,187498.5,27079.25,295,252.75,74592.5,2029,213.5,57061.75
1,7191,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,186,118.5,193.25,27,127.5,48.75,112.5,81.5,37,92.5,137940.75,112925,154675,43216.5,80568.75,32537.5,6770.5,46710,19973.75,90179.75
2,7283,M,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,1,0,1,1,1,1,0,0,0,0,1,0,1,1,0,593.5,426.25,376.25,-9.75,163,132.5,66.75,21.5,14.5,-22.75,215546,211708,227075.5,547.25,114837.75,54140,92600.75,12822.75,352.75,399.25
3,7385,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,223.25,190.25,235,17,197.75,87,130,493.5,156.5,51.25,182501,166949.25,188780,3507.5,113108.5,61596.25,127289.5,186401.5,114430.25,83217.5
4,7415,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,1113,685.25,665.75,22.75,17.5,7,20,90.75,105.5,11,180698,199563,229105.25,1575,476.5,367.5,25938,32915,45131.25,209.75
5,7423,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,258.5,166.5,282.5,-1,36,22.25,10.25,270,52.5,207,174829.75,144314.25,205137.75,562,257.25,134.5,68627.5,108870,64012.25,128146.5
6,7424,F,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,1,0,1,1,0,1893.5,1323.25,2509.75,-5,115.5,100.25,-11.25,637,1649.5,283.5,174166,201581.5,206533,15292.75,66127,48691.5,6081,157824.75,197410.5,127998.75
7,7426,M,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,0,0,1,0,0,956.75,640.25,393.75,45.25,90.25,124.25,-10,64.25,-21.5,43.75,189378.75,191103,187612,33458.5,54611.25,73298.75,50223,18252,7954.25,58212.75
8,7010,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,0,0,0,1,1,0,201.75,112.5,176.25,-18.25,-32.75,37.5,1126.25,2836.25,65.5,58.25,53927.75,33040.25,51370.75,1669,77.75,202.5,223942.75,182973.5,19613.5,16821
9,7023,M,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1047,768,833.5,3.25,81.25,85.5,6,192.75,234,34.25,193681.25,209817.5,247009.25,51569.25,133783.25,95077.25,212439,207342.75,170871,124249
10,7024,F,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,217.75,73.25,32.75,-35,-15,40.75,-19.75,15,108.5,-12,210568,182090.5,91940.25,104.5,23952,8869.5,102165.5,77164.25,152883,135.75
11,7030,M,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,1416.25,966.5,620.25,155.75,-24.25,56.25,-7,589.25,1967,-11.75,194634.25,213084.75,235449,134422.25,108.5,132.25,22784.25,187744,245384.75,150.25
12,7033,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,125.5,84.25,76.5,-10.75,52.25,46.75,184,13,2.75,64.75,89721,71318,69896.75,451.75,55780.5,36485.75,219376.25,16728.75,5152.75,101877
13,7034,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,0,1,0,1,1,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1475.25,896.5,245.5,155.5,-33.75,60.25,107.75,527.5,140.75,5.5,191514,226807,198293.75,157220,80.75,634,199925,185866.75,81829.5,33432
14,7032,F,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,815.75,567,579,3,151.5,327.25,10,373,110.25,16.75,222582.25,186373.25,198345,24216.75,113532.75,80674.75,35615.75,56992.75,24934.5,117.5
15,7053,F,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,985,989,3112.25,50,-18.25,38.5,1236.5,3190,6949,17.75,194219.75,196038.75,240821,14998.25,186.5,305.75,218797.75,167260.5,205853.5,236.25
16,7069,F,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,1,0,0,0,1,1,1,0,1,1,1,1,0,1,0,0,0,1,1,1,0,526.75,407.75,459,-22,-24.25,71.25,82,738.5,453.25,547.25,187866.75,165923.75,182536,327.25,78.25,161.25,95925.75,179473.75,133829.5,149741.25
17,7075,F,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,195,99.75,251.5,55.25,56,54.25,26.5,71,228.25,71.5,195303.5,157148.5,213394.5,83523,63041.5,62256,136019.25,72490,193180.75,100532.5
18,7076,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1027.25,593.75,439.25,17.75,-21.25,48,276.5,137.75,44.5,95.25,236139.75,203231.75,193211.25,7349.75,71.5,233,192397.75,124773.5,19715.75,73020.75
19,7077,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,19861.75,14175.25,8152,239.5,632.75,1117.5,260,808,336.25,1255.25,202796.75,238566,269013,20995.25,71204.5,111107.25,53013.25,95861,41436,123636.5
20,7090,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,48.25,6.5,47.75,-18.5,-9.5,30.5,34.25,56.25,236.5,37.25,18366.75,12916.25,45414.5,843.75,24.75,309,74029.75,68933.75,94229.75,68046.25
21,3198,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,156,71.25,184.75,94,16.25,199,38.75,827.5,245.25,88.25,160099.75,107969.75,165360.25,91536,55439.75,123372.5,90201.75,156743.5,137507.75,114457.75
22,3199,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,152.75,104.25,173.5,163,139.25,498.5,92.75,192.75,343.25,145.75,133586.75,79011.5,96320,113761,123061.75,181453,122251.5,115294.25,184101.75,119750.5
23,3231,F,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,163,142,540.5,71,198,261,590.25,177.25,145,136.25,116688.25,78382,132947.75,49724,154203.75,171685,115898.5,150849.5,70362.5,97287
24,3232,F,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,77,28.75,33.5,180,192.25,47.75,98.5,280.75,86.75,384.75,82,540.5,257.5,119283.75,83761.25,59088.5,55818.25,154151,78965
25,3234,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1049,666,2179.75,294.5,327.5,429.25,1107,133.5,124.25,130.25,189370,186347,213520,118185.5,125529.25,152546,159865.75,76959.5,99847.75,90276
26,3260,M,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,257.5,155.25,415.5,255.25,83.5,367.5,186.75,95.75,91.25,90.25,52605.75,27137,68865.5,94536.75,36669.5,114648,18603.75,75694.25,82172.75,44782.5
27,3264,F,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,935.25,484.75,2035.75,94,66.25,284,69.75,129.25,625.75,57.5,189438,136156.75,206270.5,78404.5,52268.75,70850.5,52673,81026.75,141926.75,66054.25
28,3290,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,94.25,59.5,1250,67.25,53,46,43.25,284.25,504.5,62.5,3486.75,1625.5,104987.75,407.25,65.25,183,3850.75,22469.5,39004.5,126
29,3292,F,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,397,270.25,962.5,176,278.75,553.5,543.5,4591.5,552.75,3685.25,28118,16859.5,52829.25,6405.5,24502,43367.25,73615.5,155818.5,43389.5,139235.25
30,3299,F,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,902.75,534,884.25,755.5,184.25,777,29.25,59.25,44,199,192784.75,164263.75,212850.25,154614.25,100406,171900.5,29302.25,48625.25,2987,106544.5
31,3320,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1713.75,1132.5,485.25,2328.5,644,1482.5,265.75,783,2884.5,222,131839.5,96653.5,61990.25,141618.75,75492.25,109542.75,63762.5,116054.25,184010.75,33131
32,3322,M,1,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1703.75,921.5,11201.25,1505.25,28.5,47,604.5,1584.5,1238.75,486.75,154030.25,99126.5,220083,126364.75,74.75,220.5,92663.75,138767.25,95991,50602
33,3323,F,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1172.25,435.25,1055.25,186.25,311,299.75,184,260.25,301.25,245.5,174303.5,110687.5,168968.25,48504.25,85379.5,79575,101337,61349,88145.75,83502.75
34,3324,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,205.5,139.5,828,62.25,747,481,163.5,1048.5,1124.75,694.25,29042.5,8420.5,106150.75,11227.25,140056.5,98418.75,70178,173119.75,149510.75,127266.25
35,3339,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,2327.5,1217.5,2915.25,359,786.25,984.75,1652.75,961.75,846.25,500.25,42543,22916.5,83789.75,53416.75,118773.5,145619.75,36279.25,171429.25,150600,113612.5
36,3341,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4118.25,2824.25,4514.75,266.75,643,950.5,705.5,408.5,601.25,764.75,28486.25,13434,71599.25,62651.75,81125,87085.5,65016,38125.75,62006.75,109778
37,3346,F,1,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,322.5,249,630.5,53.5,258.25,339.75,36.25,26.75,50.75,82.75,129343.75,80787.5,211443.5,65057,176434.5,167895.5,635.25,190.5,74.75,108.5
38,3362,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,123.75,98.25,333.25,50.75,19.75,-21,15.25,189.25,115,88,116285.5,75943,206502.75,40823.75,36,219.75,61198.25,135511.25,84225.75,84796.5
39,3365,F,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,67.25,64,195.5,42.25,192.25,495.5,321.25,197.25,11,162.5,35396.5,23123.25,109559,4637.5,100263.25,108335,126723.75,93123.25,1859.25,90404.25
40,3381,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1744.5,1338.5,2333,242.75,8.25,43.75,302.5,184.25,313.5,15.5,62487.5,40178.5,128598.75,17942.5,117488.75,110795.75,76884.25,72785,68638,136637.5
41,3386,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,159.25,98,236.25,21,-23,18.25,102.5,38.75,62.5,126.75,8619.5,4262,10107,2888.75,167.25,320,141567.75,89777.75,41388.25,130774.75
42,3391,F,0,1,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2232.25,1480.5,5355.5,333.75,364,777.25,640.75,549.75,333.75,762.75,120259,85601,199734.5,75635,126.25,190.5,130148,52106.5,1405.75,48900.25
43,3400,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,35,-4.25,74.75,9.5,5.5,22.75,149.75,54,92.5,-10.25,34301.5,18230,91171.25,5333.75,88.75,656.5,116370.25,78160.25,69868.5,245
44,3401,F,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,22.25,34,77.25,26.25,28.5,99.25,62.5,245.25,234.5,42,42653.5,32694.25,75011.75,7132.25,64707,26211,75262.5,149438,127294.25,70003.75
45,3404,F,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,89.5,56.5,145.25,55.5,9,-7,51.5,184.25,99.5,10.75,28745,18876.5,62798.5,35519.25,120828.25,93548,110433.75,94926.5,82881.25,3930.5
46,3427,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,0,1,0,0,0,1,0,0,135.25,85,280.5,18,255,1311.5,39.5,92,52.75,1,147871.75,82947.5,196497.25,23175.5,131601.5,196282.25,103385.5,85933.75,58069,158.25
47,3438,M,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,792.75,554.75,1564.5,10.25,43,138.75,154.5,32,261.75,98.75,166384.5,130882,149708.25,80187.75,35784,21164.5,88320.75,52044.25,70367.25,96811.75
48,3459,F,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,-12.75,-4.75,24.5,-12.5,53.25,77.5,28.75,18,22.75,35,7876.5,8056,23335.25,2830.25,108337.5,85071.5,93826,127659.5,61743.25,103167.5
49,3460,M,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,92.5,22.75,64,11.75,95.5,179.25,910.5,150.75,314,107.5,70391.25,25811,40673.75,13387.5,46716,28620.5,136487,55973.5,94283.5,46972.25
50,3471,M,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79,61.5,148,97.25,-8.75,0.5,163,-34.5,13,40,87968.5,56701,58296.5,85466.5,95,883.75,120276.25,7171,10126.25,47765.75
51,3474,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,206.25,133.75,630,98.5,24,46.75,1159.75,26.25,41.5,203.25,82298.25,60154,180910.25,68814,16576.25,13246.25,161775.25,21034.75,24299,105486.75
52,3475,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,101,62.5,47.75,9.5,33.5,126.75,30.5,20.5,34,51.75,41740.75,18502.25,70044.5,13146.75,65614,47762.75,83818.25,72836,28165.75,72419.25
53,3503,M,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,199.25,125.75,354.5,82,727,414.25,139.75,66,105.75,109.25,75647.5,47629,94516.5,37940.5,110333.5,102381.75,94092.75,28678,35701.25,47221.75
54,3532,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,348,257.25,721.75,8.5,165.5,181.25,186.5,303,158,210,186853.5,164726.25,216375.75,6952.5,122881.25,37392,93650.25,129479.5,17048.25,110266.5
55,3556,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,14,35.75,-14.5,128.75,260.5,248.5,383.5,0.75,8,13681.25,4201.25,16396,2805,111138.5,58484.75,120214,53314,995.25,308.25
56,3582,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,177.25,136.75,323,-3.5,-12,9.25,-0.5,-19.25,27,47.75,183541.5,141921.25,198390.75,1621.25,103,156.5,44503,23156,20233.5,46331.75
57,3580,F,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,8.25,13.25,38.75,3.25,79.5,160.5,9.5,234.75,240.5,118.75,8153,4811.25,38304.25,11596.75,61753,58008.5,63939.75,108580,96489.25,81423.5
58,3591,F,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1025.25,660,2340.5,128,238,389.5,1229.75,312,226.5,433.5,65804,43098.75,56725.5,48180.5,109057.75,69093,115956.5,49050.25,11159,127044.25
59,3593,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,74.25,28.5,389.5,10,106.75,126.75,73.75,91.75,216.75,73,21439,12717.25,58761,8796.75,95656.25,50988,68021,35693,64579.75,69569.25

# Merge Sinai and Emory

In [10]:
# sinai = pd.read_csv("data_cleaned/UCSF_8_21_2024_DATAEXPORT_original_survey.csv").rename(columns = {"comorb_selfreport_v2___13": "comorb_selfreport_13"})
sinai = pd.read_csv("data_cleaned/UCSF_2_4_25_most_recent_surveys_100_n825.csv").rename(columns = {"comorb_selfreport_v2___13": "comorb_selfreport_13"})
sinai

,record_id,yale_id,sex,currentsymptoms_1,currentsymptoms_2,currentsymptoms_3,currentsymptoms_4,currentsymptoms_5,currentsymptoms_6,currentsymptoms_7,currentsymptoms_8,currentsymptoms_9,currentsymptoms_10,currentsymptoms_11,currentsymptoms_12,currentsymptoms_13,currentsymptoms_14,currentsymptoms_15,currentsymptoms_16,currentsymptoms_17,currentsymptoms_18,currentsymptoms_19,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_24,currentsymptoms_25,currentsymptoms_26,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_31,currentsymptoms_32,currentsymptoms_33,currentsymptoms_34,currentsymptoms_35,currentsymptoms_36,currentsymptoms_37,currentsymptoms_38,currentsymptoms_39,currentsymptoms_40,currentsymptoms_41,currentsymptoms_42,currentsymptoms_43,currentsymptoms_44,currentsymptoms_45,currentsymptoms_46,comorb_selfreport_1,comorb_selfreport_2,comorb_selfreport_3,comorb_selfreport_4,comorb_selfreport_5,comorb_selfreport_6,comorb_selfreport_7,comorb_selfreport_8,comorb_selfreport_9,comorb_selfreport_10,comorb_selfreport_11,comorb_selfreport_12,comorb_selfreport_13,comorb_selfreport_14,comorb_selfreport_15,comorb_selfreport_16,comorb_selfreport_17,comorb_selfreport_18,comorb_selfreport_19,comorb_selfreport_20,eq5vas
0,2,79,M,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,75.0
1,3,NaN,F,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
2,7,NaN,M,0,1,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,1,0,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,1,0,1,0,1,0,0,1,1,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
3,8,NaN,F,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0
4,9,NaN,F,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,1,0,1,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
820,1272,NaN,F,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,85.0
821,1273,NaN,M,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0
822,1274,NaN,M,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,25.0
823,1275,NaN,F,0,1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,1,1,1,0,1,0,0,1,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,71.0
824,1276,NaN,F,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,75.0

In [11]:
# emory = pd.read_csv("data_cleaned/data_collection_for_sinai.csv").rename(columns = {"Subject #": "record_id"})
emory = data.copy()
emory

,record_id,sex,comorb_selfreport_1,comorb_selfreport_2,comorb_selfreport_3,comorb_selfreport_4,comorb_selfreport_5,comorb_selfreport_6,comorb_selfreport_7,comorb_selfreport_8,comorb_selfreport_9,comorb_selfreport_10,comorb_selfreport_11,comorb_selfreport_12,comorb_selfreport_13,comorb_selfreport_14,comorb_selfreport_15,comorb_selfreport_16,comorb_selfreport_17,comorb_selfreport_18,currentsymptoms_1,currentsymptoms_2,currentsymptoms_3,currentsymptoms_4,currentsymptoms_6,currentsymptoms_7,currentsymptoms_8,currentsymptoms_9,currentsymptoms_10,currentsymptoms_11,currentsymptoms_12,currentsymptoms_13,currentsymptoms_15,currentsymptoms_16,currentsymptoms_17,currentsymptoms_18,currentsymptoms_19,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_24,currentsymptoms_25,currentsymptoms_26,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_31,currentsymptoms_32,currentsymptoms_33,currentsymptoms_34,currentsymptoms_35,currentsymptoms_36,currentsymptoms_39,currentsymptoms_40,currentsymptoms_41,currentsymptoms_42,currentsymptoms_43,currentsymptoms_44,rbd_mensa_igg,s1_mensa_igg,s2_mensa_igg,np_mensa_igg,cmv_gb_1_mensa_igg,cmv_pentamer_mensa_igg,ebv_ebna1_mensa_igg,ebv_vca_mensa_igg,ebv_gp350_mensa_igg,hsv2_gd_mensa_igg,rbd_serum_igg,s1_serum_igg,s2_serum_igg,np_serum_igg,cmv_gb_1_serum_igg,cmv_pentamer_serum_igg,ebv_ebna1_serum_igg,ebv_vca_serum_igg,ebv_gp350_serum_igg,hsv2_gd_serum_igg
0,3633,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,61.25,84.5,59,11.75,25.5,1,7.25,39.25,0.75,-8.5,197923,181317,187498.5,27079.25,295,252.75,74592.5,2029,213.5,57061.75
1,7191,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,0,186,118.5,193.25,27,127.5,48.75,112.5,81.5,37,92.5,137940.75,112925,154675,43216.5,80568.75,32537.5,6770.5,46710,19973.75,90179.75
2,7283,M,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,1,0,1,1,1,1,0,0,0,0,1,0,1,1,0,593.5,426.25,376.25,-9.75,163,132.5,66.75,21.5,14.5,-22.75,215546,211708,227075.5,547.25,114837.75,54140,92600.75,12822.75,352.75,399.25
3,7385,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,1,0,1,0,0,223.25,190.25,235,17,197.75,87,130,493.5,156.5,51.25,182501,166949.25,188780,3507.5,113108.5,61596.25,127289.5,186401.5,114430.25,83217.5
4,7415,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,1113,685.25,665.75,22.75,17.5,7,20,90.75,105.5,11,180698,199563,229105.25,1575,476.5,367.5,25938,32915,45131.25,209.75
5,7423,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,1,0,258.5,166.5,282.5,-1,36,22.25,10.25,270,52.5,207,174829.75,144314.25,205137.75,562,257.25,134.5,68627.5,108870,64012.25,128146.5
6,7424,F,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,1,0,1,1,0,1893.5,1323.25,2509.75,-5,115.5,100.25,-11.25,637,1649.5,283.5,174166,201581.5,206533,15292.75,66127,48691.5,6081,157824.75,197410.5,127998.75
7,7426,M,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,1,1,0,0,1,1,1,0,0,1,0,0,0,1,0,0,956.75,640.25,393.75,45.25,90.25,124.25,-10,64.25,-21.5,43.75,189378.75,191103,187612,33458.5,54611.25,73298.75,50223,18252,7954.25,58212.75
8,7010,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,1,1,1,1,0,1,0,0,0,0,1,1,0,201.75,112.5,176.25,-18.25,-32.75,37.5,1126.25,2836.25,65.5,58.25,53927.75,33040.25,51370.75,1669,77.75,202.5,223942.75,182973.5,19613.5,16821
9,7023,M,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1047,768,833.5,3.25,81.25,85.5,6,192.75,234,34.25,193681.25,209817.5,247009.25,51569.25,133783.25,95077.25,212439,207342.75,170871,124249
10,7024,F,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,1,0,0,0,0,1,0,0,217.75,73.25,32.75,-35,-15,40.75,-19.75,15,108.5,-12,210568,182090.5,91940.25,104.5,23952,8869.5,102165.5,77164.25,152883,135.75
11,7030,M,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,0,0,0,1,1,0,1416.25,966.5,620.25,155.75,-24.25,56.25,-7,589.25,1967,-11.75,194634.25,213084.75,235449,134422.25,108.5,132.25,22784.25,187744,245384.75,150.25
12,7033,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,125.5,84.25,76.5,-10.75,52.25,46.75,184,13,2.75,64.75,89721,71318,69896.75,451.75,55780.5,36485.75,219376.25,16728.75,5152.75,101877
13,7034,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,1,1,0,1,0,1,1,1,1,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,1,0,0,0,0,1475.25,896.5,245.5,155.5,-33.75,60.25,107.75,527.5,140.75,5.5,191514,226807,198293.75,157220,80.75,634,199925,185866.75,81829.5,33432
14,7032,F,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,1,1,0,0,815.75,567,579,3,151.5,327.25,10,373,110.25,16.75,222582.25,186373.25,198345,24216.75,113532.75,80674.75,35615.75,56992.75,24934.5,117.5
15,7053,F,0,0,0,0,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,1,1,1,1,0,0,1,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,985,989,3112.25,50,-18.25,38.5,1236.5,3190,6949,17.75,194219.75,196038.75,240821,14998.25,186.5,305.75,218797.75,167260.5,205853.5,236.25
16,7069,F,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,1,0,0,0,1,1,1,0,1,1,1,1,0,1,0,0,0,1,1,1,0,526.75,407.75,459,-22,-24.25,71.25,82,738.5,453.25,547.25,187866.75,165923.75,182536,327.25,78.25,161.25,95925.75,179473.75,133829.5,149741.25
17,7075,F,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,195,99.75,251.5,55.25,56,54.25,26.5,71,228.25,71.5,195303.5,157148.5,213394.5,83523,63041.5,62256,136019.25,72490,193180.75,100532.5
18,7076,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,1027.25,593.75,439.25,17.75,-21.25,48,276.5,137.75,44.5,95.25,236139.75,203231.75,193211.25,7349.75,71.5,233,192397.75,124773.5,19715.75,73020.75
19,7077,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,19861.75,14175.25,8152,239.5,632.75,1117.5,260,808,336.25,1255.25,202796.75,238566,269013,20995.25,71204.5,111107.25,53013.25,95861,41436,123636.5
20,7090,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,48.25,6.5,47.75,-18.5,-9.5,30.5,34.25,56.25,236.5,37.25,18366.75,12916.25,45414.5,843.75,24.75,309,74029.75,68933.75,94229.75,68046.25
21,3198,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,156,71.25,184.75,94,16.25,199,38.75,827.5,245.25,88.25,160099.75,107969.75,165360.25,91536,55439.75,123372.5,90201.75,156743.5,137507.75,114457.75
22,3199,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,152.75,104.25,173.5,163,139.25,498.5,92.75,192.75,343.25,145.75,133586.75,79011.5,96320,113761,123061.75,181453,122251.5,115294.25,184101.75,119750.5
23,3231,F,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,163,142,540.5,71,198,261,590.25,177.25,145,136.25,116688.25,78382,132947.75,49724,154203.75,171685,115898.5,150849.5,70362.5,97287
24,3232,F,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51,77,28.75,33.5,180,192.25,47.75,98.5,280.75,86.75,384.75,82,540.5,257.5,119283.75,83761.25,59088.5,55818.25,154151,78965
25,3234,F,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1049,666,2179.75,294.5,327.5,429.25,1107,133.5,124.25,130.25,189370,186347,213520,118185.5,125529.25,152546,159865.75,76959.5,99847.75,90276
26,3260,M,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,257.5,155.25,415.5,255.25,83.5,367.5,186.75,95.75,91.25,90.25,52605.75,27137,68865.5,94536.75,36669.5,114648,18603.75,75694.25,82172.75,44782.5
27,3264,F,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,935.25,484.75,2035.75,94,66.25,284,69.75,129.25,625.75,57.5,189438,136156.75,206270.5,78404.5,52268.75,70850.5,52673,81026.75,141926.75,66054.25
28,3290,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,94.25,59.5,1250,67.25,53,46,43.25,284.25,504.5,62.5,3486.75,1625.5,104987.75,407.25,65.25,183,3850.75,22469.5,39004.5,126
29,3292,F,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,1,0,0,0,1,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,397,270.25,962.5,176,278.75,553.5,543.5,4591.5,552.75,3685.25,28118,16859.5,52829.25,6405.5,24502,43367.25,73615.5,155818.5,43389.5,139235.25
30,3299,F,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,902.75,534,884.25,755.5,184.25,777,29.25,59.25,44,199,192784.75,164263.75,212850.25,154614.25,100406,171900.5,29302.25,48625.25,2987,106544.5
31,3320,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1713.75,1132.5,485.25,2328.5,644,1482.5,265.75,783,2884.5,222,131839.5,96653.5,61990.25,141618.75,75492.25,109542.75,63762.5,116054.25,184010.75,33131
32,3322,M,1,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1703.75,921.5,11201.25,1505.25,28.5,47,604.5,1584.5,1238.75,486.75,154030.25,99126.5,220083,126364.75,74.75,220.5,92663.75,138767.25,95991,50602
33,3323,F,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1172.25,435.25,1055.25,186.25,311,299.75,184,260.25,301.25,245.5,174303.5,110687.5,168968.25,48504.25,85379.5,79575,101337,61349,88145.75,83502.75
34,3324,F,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,205.5,139.5,828,62.25,747,481,163.5,1048.5,1124.75,694.25,29042.5,8420.5,106150.75,11227.25,140056.5,98418.75,70178,173119.75,149510.75,127266.25
35,3339,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,2327.5,1217.5,2915.25,359,786.25,984.75,1652.75,961.75,846.25,500.25,42543,22916.5,83789.75,53416.75,118773.5,145619.75,36279.25,171429.25,150600,113612.5
36,3341,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4118.25,2824.25,4514.75,266.75,643,950.5,705.5,408.5,601.25,764.75,28486.25,13434,71599.25,62651.75,81125,87085.5,65016,38125.75,62006.75,109778
37,3346,F,1,0,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,322.5,249,630.5,53.5,258.25,339.75,36.25,26.75,50.75,82.75,129343.75,80787.5,211443.5,65057,176434.5,167895.5,635.25,190.5,74.75,108.5
38,3362,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,123.75,98.25,333.25,50.75,19.75,-21,15.25,189.25,115,88,116285.5,75943,206502.75,40823.75,36,219.75,61198.25,135511.25,84225.75,84796.5
39,3365,F,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,67.25,64,195.5,42.25,192.25,495.5,321.25,197.25,11,162.5,35396.5,23123.25,109559,4637.5,100263.25,108335,126723.75,93123.25,1859.25,90404.25
40,3381,F,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1744.5,1338.5,2333,242.75,8.25,43.75,302.5,184.25,313.5,15.5,62487.5,40178.5,128598.75,17942.5,117488.75,110795.75,76884.25,72785,68638,136637.5
41,3386,F,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,159.25,98,236.25,21,-23,18.25,102.5,38.75,62.5,126.75,8619.5,4262,10107,2888.75,167.25,320,141567.75,89777.75,41388.25,130774.75
42,3391,F,0,1,0,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,2232.25,1480.5,5355.5,333.75,364,777.25,640.75,549.75,333.75,762.75,120259,85601,199734.5,75635,126.25,190.5,130148,52106.5,1405.75,48900.25
43,3400,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,35,-4.25,74.75,9.5,5.5,22.75,149.75,54,92.5,-10.25,34301.5,18230,91171.25,5333.75,88.75,656.5,116370.25,78160.25,69868.5,245
44,3401,F,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,22.25,34,77.25,26.25,28.5,99.25,62.5,245.25,234.5,42,42653.5,32694.25,75011.75,7132.25,64707,26211,75262.5,149438,127294.25,70003.75
45,3404,F,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,89.5,56.5,145.25,55.5,9,-7,51.5,184.25,99.5,10.75,28745,18876.5,62798.5,35519.25,120828.25,93548,110433.75,94926.5,82881.25,3930.5
46,3427,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,0,0,1,1,1,0,0,0,0,0,1,1,1,1,0,1,0,0,0,1,0,0,135.25,85,280.5,18,255,1311.5,39.5,92,52.75,1,147871.75,82947.5,196497.25,23175.5,131601.5,196282.25,103385.5,85933.75,58069,158.25
47,3438,M,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,792.75,554.75,1564.5,10.25,43,138.75,154.5,32,261.75,98.75,166384.5,130882,149708.25,80187.75,35784,21164.5,88320.75,52044.25,70367.25,96811.75
48,3459,F,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,-12.75,-4.75,24.5,-12.5,53.25,77.5,28.75,18,22.75,35,7876.5,8056,23335.25,2830.25,108337.5,85071.5,93826,127659.5,61743.25,103167.5
49,3460,M,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,92.5,22.75,64,11.75,95.5,179.25,910.5,150.75,314,107.5,70391.25,25811,40673.75,13387.5,46716,28620.5,136487,55973.5,94283.5,46972.25
50,3471,M,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,79,61.5,148,97.25,-8.75,0.5,163,-34.5,13,40,87968.5,56701,58296.5,85466.5,95,883.75,120276.25,7171,10126.25,47765.75
51,3474,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,206.25,133.75,630,98.5,24,46.75,1159.75,26.25,41.5,203.25,82298.25,60154,180910.25,68814,16576.25,13246.25,161775.25,21034.75,24299,105486.75
52,3475,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,101,62.5,47.75,9.5,33.5,126.75,30.5,20.5,34,51.75,41740.75,18502.25,70044.5,13146.75,65614,47762.75,83818.25,72836,28165.75,72419.25
53,3503,M,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,199.25,125.75,354.5,82,727,414.25,139.75,66,105.75,109.25,75647.5,47629,94516.5,37940.5,110333.5,102381.75,94092.75,28678,35701.25,47221.75
54,3532,M,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,348,257.25,721.75,8.5,165.5,181.25,186.5,303,158,210,186853.5,164726.25,216375.75,6952.5,122881.25,37392,93650.25,129479.5,17048.25,110266.5
55,3556,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,14,35.75,-14.5,128.75,260.5,248.5,383.5,0.75,8,13681.25,4201.25,16396,2805,111138.5,58484.75,120214,53314,995.25,308.25
56,3582,F,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,177.25,136.75,323,-3.5,-12,9.25,-0.5,-19.25,27,47.75,183541.5,141921.25,198390.75,1621.25,103,156.5,44503,23156,20233.5,46331.75
57,3580,F,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,8.25,13.25,38.75,3.25,79.5,160.5,9.5,234.75,240.5,118.75,8153,4811.25,38304.25,11596.75,61753,58008.5,63939.75,108580,96489.25,81423.5
58,3591,F,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1025.25,660,2340.5,128,238,389.5,1229.75,312,226.5,433.5,65804,43098.75,56725.5,48180.5,109057.75,69093,115956.5,49050.25,11159,127044.25
59,3593,F,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,74.25,28.5,389.5,10,106.75,126.75,73.75,91.75,216.75,73,21439,12717.25,58761,8796.75,95656.25,50988,68021,35693,64579.75,69569.25

In [12]:
columns = sorted(list(set(sinai.columns) & set(emory.columns)))
columns

['comorb_selfreport_1',
 'comorb_selfreport_10',
 'comorb_selfreport_11',
 'comorb_selfreport_12',
 'comorb_selfreport_13',
 'comorb_selfreport_14',
 'comorb_selfreport_15',
 'comorb_selfreport_16',
 'comorb_selfreport_17',
 'comorb_selfreport_18',
 'comorb_selfreport_2',
 'comorb_selfreport_3',
 'comorb_selfreport_4',
 'comorb_selfreport_5',
 'comorb_selfreport_6',
 'comorb_selfreport_7',
 'comorb_selfreport_8',
 'comorb_selfreport_9',
 'currentsymptoms_1',
 'currentsymptoms_10',
 'currentsymptoms_11',
 'currentsymptoms_12',
 'currentsymptoms_13',
 'currentsymptoms_15',
 'currentsymptoms_16',
 'currentsymptoms_17',
 'currentsymptoms_18',
 'currentsymptoms_19',
 'currentsymptoms_2',
 'currentsymptoms_20',
 'currentsymptoms_21',
 'currentsymptoms_22',
 'currentsymptoms_23',
 'currentsymptoms_24',
 'currentsymptoms_25',
 'currentsymptoms_26',
 'currentsymptoms_27',
 'currentsymptoms_28',
 'currentsymptoms_29',
 'currentsymptoms_3',
 'currentsymptoms_30',
 'currentsymptoms_31',
 'currentsymptoms_32',
 'currentsymptoms_33',
 'currentsymptoms_34',
 'currentsymptoms_35',
 'currentsymptoms_36',
 'currentsymptoms_39',
 'currentsymptoms_4',
 'currentsymptoms_40',
 'currentsymptoms_41',
 'currentsymptoms_42',
 'currentsymptoms_43',
 'currentsymptoms_44',
 'currentsymptoms_6',
 'currentsymptoms_7',
 'currentsymptoms_8',
 'currentsymptoms_9',
 'record_id',
 'sex']

In [16]:
columns = sorted(list(set(sinai.columns) & set(emory.columns)))
columns.append("yale_id")
merged = pd.concat([sinai[columns], emory[columns[:-1]]])
columns = list(filter(re.compile("currentsymptoms_.*").match, merged.columns))
columns = [int(val.split("_")[-1]) for val in columns]
columns = sorted(columns)
columns = [f"currentsymptoms_{i}" for i in columns]
columns_ = ['record_id', 'yale_id', 'sex']
columns_.extend(columns)
columns = list(filter(re.compile("comorb_selfreport_.*").match, merged.columns))
columns = [int(val.split("_")[-1]) for val in columns]
columns = sorted(columns)
columns = [f"comorb_selfreport_{i}" for i in columns]
columns_.extend(columns)
columns = columns_[:]
merged = merged[columns]
merged

,record_id,yale_id,sex,currentsymptoms_1,currentsymptoms_2,currentsymptoms_3,currentsymptoms_4,currentsymptoms_6,currentsymptoms_7,currentsymptoms_8,currentsymptoms_9,currentsymptoms_10,currentsymptoms_11,currentsymptoms_12,currentsymptoms_13,currentsymptoms_15,currentsymptoms_16,currentsymptoms_17,currentsymptoms_18,currentsymptoms_19,currentsymptoms_20,currentsymptoms_21,currentsymptoms_22,currentsymptoms_23,currentsymptoms_24,currentsymptoms_25,currentsymptoms_26,currentsymptoms_27,currentsymptoms_28,currentsymptoms_29,currentsymptoms_30,currentsymptoms_31,currentsymptoms_32,currentsymptoms_33,currentsymptoms_34,currentsymptoms_35,currentsymptoms_36,currentsymptoms_39,currentsymptoms_40,currentsymptoms_41,currentsymptoms_42,currentsymptoms_43,currentsymptoms_44,comorb_selfreport_1,comorb_selfreport_2,comorb_selfreport_3,comorb_selfreport_4,comorb_selfreport_5,comorb_selfreport_6,comorb_selfreport_7,comorb_selfreport_8,comorb_selfreport_9,comorb_selfreport_10,comorb_selfreport_11,comorb_selfreport_12,comorb_selfreport_13,comorb_selfreport_14,comorb_selfreport_15,comorb_selfreport_16,comorb_selfreport_17,comorb_selfreport_18
0,2,79,M,0,1,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3,NaN,F,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,NaN,M,0,1,0,0,1,1,0,0,0,0,0,1,1,0,0,1,0,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,1,0,1,0,0,1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,NaN,F,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9,NaN,F,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,1,0,1,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,3556,NaN,F,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
56,3582,NaN,F,0,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
57,3580,NaN,F,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0
58,3591,NaN,F,1,1,0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,0,0,1,0,0,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
59,3593,NaN,F,0,1,1,1,0,1,0,0,0,0,0,1,1,1,1,1,0,1,1,0,1,0,0,0,1,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0

In [18]:
len(np.unique(merged["yale_id"].astype(str)))

135

In [19]:
# merged.to_csv("data_cleaned/emory_and_sinai_n885.csv", index = False)

In [ ]:
comorb = ["Hypertension", "Diabetes", "Chronic Kidney Disease", "Chronic Liver Disease (i.e Cirrhosis, Hepatitis B)", "Asthma", "Chronic Obstructive Pulmonary Disease", "Other Chronic Lung Disease", "Stroke", "Spinal Cord Injury", "Other Neurological Disease (Parkinson, Epilepsy, Dementia)", "Obesity", "Immunodeficiency (i.e auto-immune disease)", "Cancer", "Anxiety", "Depression", "Other Psychiatric Disease", "Eating disorder", "Inflammatory Bowel Disease/ Irritable Bowel Syndrome", "Other - please specify below", "None"]
comorb_dict = dict(zip(["comorb_selfreport_" + str(i) for i in range(1, len(comorb) + 1)], comorb))
del comorb_dict["comorb_selfreport_19"]
del comorb_dict["comorb_selfreport_20"]
comorb_dict

In [ ]:
clusters_15 = [8, 1, 1, 6, 8, 6, 8, 6, 6, 1, 8, 1, 8, 8, 1, 1, 6, 8, 1, 1, 1, 8, 1, 6, 1, 8, 1, 8, 8, 6, 6, 1, 6, 6, 1, 6, 8, 8, 6, 6, 6, 8, 6, 6, 1, 1, 1, 8, 1, 8, 8, 1, 6, 8, 6, 6, 1, 10, 6, 8, 1, 6, 8, 6, 1, 11, 1, 1, 1, 6, 1, 1, 6, 6, 6, 8, 8, 6, 6, 6, 6, 1, 6, 6, 1, 1, 1, 1, 6, 1, 10, 6, 7, 1, 1, 1, 7, 8, 1, 8, 6, 1, 8, 1, 1, 8, 4, 1, 1, 2, 1, 1, 9, 1, 2, 3, 2, 1, 4, 3, 10, 1, 1, 5, 4, 7, 3, 7, 11, 1, 1, 3, 2, 1, 2, 3, 2, 11, 1, 1, 7, 2, 2, 3, 2, 11, 1, 2, 3, 10, 2, 3, 1, 9, 4, 1, 5, 13, 3, 1, 3, 1, 1, 4, 1, 9, 14, 1, 1, 1, 10, 13, 9, 3, 10, 1, 1, 1, 1, 1, 1, 11, 1, 1, 1, 1, 10, 5, 3, 2, 1, 2, 1, 15, 1, 4, 2, 1, 11, 1, 3, 1, 1, 1, 15, 1, 14, 2, 5, 1, 1, 1, 3, 13, 12, 5, 1, 1, 7, 1, 5, 11, 5, 1, 2, 1, 1, 1, 1, 14, 1, 3, 1, 2, 5, 4, 1, 1, 4, 1, 5, 6, 1, 13, 1, 4, 2, 3, 1, 3, 1, 11, 4, 1, 7, 4, 1, 9, 1, 12, 5, 1, 1, 11, 3, 2, 1, 1, 2, 3, 1, 4, 4, 3, 5, 1, 4, 12, 13, 2, 10, 4, 1, 2, 3, 11, 1, 5, 7, 5, 11, 12, 4, 1, 3, 1, 1, 1, 1, 1, 9, 1, 13, 1, 2, 12, 2, 2, 1, 5, 7, 1, 5, 11, 5, 1, 4, 1, 3, 12, 13, 2, 4, 3, 1, 4, 1, 13, 4, 1, 1, 12, 3, 4, 1, 1, 1, 1, 1, 12, 1, 1, 2, 7, 9, 1, 9, 7, 3, 2, 1, 3, 2, 2, 4, 4, 7, 4, 1, 9, 15, 1, 2, 1, 10, 2, 7, 1, 1, 9, 1, 10, 3, 1, 1, 1, 1, 14, 2, 12, 3, 3, 1, 4, 15, 5, 5, 9, 5, 5, 2, 1, 14, 2, 1, 1, 13, 5, 1, 11, 1, 2, 1, 10, 13, 1, 2, 1, 1, 2, 3, 1, 1, 5, 9, 10, 10, 3, 9, 2, 13, 3, 1, 5, 3, 13, 1, 1, 2, 3, 1, 13, 9, 12, 3, 7, 2, 5, 14, 1, 2, 1, 10, 9, 5, 4, 15, 1, 10, 9, 1, 9, 4, 1, 1, 2, 2, 5, 1, 2, 1, 10, 1, 7, 7, 1, 7, 1, 14, 4, 1, 7, 10, 12, 1, 5, 1, 2, 4, 12, 5, 12, 9, 10, 2, 2, 5, 11, 13, 2, 7, 5, 5, 4, 14, 10, 1, 4, 15, 12, 10, 11, 3, 7, 2, 2, 1, 7, 7, 1, 10, 13, 4, 10, 1, 1, 14, 2, 7, 1, 11, 1, 4, 11, 12, 5, 1, 2, 1, 9, 1, 1, 1, 4, 12, 14, 1, 3, 14, 7, 1, 1, 1, 1, 2, 3, 12, 9, 7, 1, 12, 1, 9, 4, 2, 1, 4, 1, 2, 1, 5, 11, 9, 11, 4, 2, 12, 10, 5, 1, 5, 1, 1, 9, 3, 1, 2, 9, 2, 1, 1, 14, 4, 2, 9, 15, 1, 5, 1, 4, 2, 2, 4, 1, 2, 1, 2, 13, 3, 2, 12, 10, 13, 2, 2, 2, 2, 1, 1, 12, 5, 4, 11, 3, 13, 11, 3, 15, 7, 4, 3, 11, 2, 5, 1, 11, 3, 1, 3, 2, 4, 4, 2, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 10, 1, 11, 1, 4, 5]
clusters_16 = [11, 1, 1, 10, 11, 13, 11, 13, 10, 1, 11, 1, 11, 11, 1, 1, 13, 11, 1, 1, 1, 11, 1, 10, 1, 11, 1, 11, 11, 13, 13, 10, 10, 10, 1, 13, 11, 11, 13, 13, 13, 11, 13, 13, 10, 1, 1, 11, 1, 11, 11, 1, 13, 11, 10, 10, 1, 8, 10, 11, 1, 13, 11, 10, 10, 16, 1, 1, 1, 13, 10, 1, 13, 13, 13, 10, 11, 13, 13, 13, 13, 10, 10, 10, 10, 1, 1, 1, 10, 10, 8, 13, 3, 1, 1, 1, 9, 11, 1, 11, 13, 1, 11, 1, 1, 11, 2, 1, 1, 3, 1, 1, 12, 1, 1, 3, 1, 1, 2, 1, 8, 1, 1, 6, 2, 3, 7, 3, 16, 5, 1, 7, 4, 1, 4, 1, 4, 16, 1, 1, 3, 4, 4, 7, 4, 4, 1, 1, 7, 8, 1, 2, 1, 12, 2, 1, 6, 14, 2, 1, 7, 1, 1, 12, 4, 15, 2, 1, 1, 5, 8, 14, 12, 2, 8, 1, 5, 1, 1, 1, 1, 16, 1, 1, 1, 1, 8, 6, 7, 3, 10, 5, 1, 7, 1, 2, 1, 1, 16, 1, 1, 1, 5, 1, 7, 1, 3, 4, 6, 1, 1, 1, 2, 14, 9, 6, 1, 1, 9, 1, 6, 4, 6, 1, 1, 1, 1, 1, 5, 3, 1, 7, 1, 3, 6, 2, 1, 1, 2, 1, 6, 10, 1, 14, 1, 2, 8, 1, 1, 1, 1, 4, 2, 5, 9, 2, 1, 15, 4, 9, 6, 1, 1, 16, 3, 3, 1, 1, 1, 2, 1, 12, 2, 2, 6, 1, 2, 9, 14, 1, 8, 2, 1, 3, 1, 4, 1, 6, 3, 6, 16, 9, 2, 1, 4, 1, 1, 1, 1, 1, 12, 1, 14, 4, 1, 9, 4, 1, 1, 6, 3, 1, 6, 4, 6, 1, 2, 1, 7, 14, 14, 1, 2, 2, 1, 2, 1, 14, 2, 5, 1, 14, 7, 2, 1, 1, 1, 1, 1, 9, 5, 1, 3, 3, 12, 4, 12, 3, 3, 5, 1, 1, 5, 1, 2, 2, 3, 2, 10, 12, 7, 5, 1, 1, 8, 3, 9, 1, 1, 12, 1, 8, 7, 1, 1, 1, 5, 15, 1, 15, 7, 7, 5, 2, 7, 6, 6, 12, 6, 6, 10, 1, 2, 1, 1, 5, 14, 6, 1, 4, 1, 4, 1, 8, 14, 1, 1, 1, 1, 5, 7, 1, 5, 6, 12, 8, 8, 3, 15, 1, 14, 1, 5, 6, 7, 14, 1, 1, 4, 1, 1, 14, 12, 9, 7, 3, 1, 6, 15, 5, 3, 1, 8, 12, 6, 12, 7, 1, 8, 15, 1, 12, 2, 5, 1, 3, 1, 6, 1, 4, 1, 8, 5, 3, 9, 5, 9, 4, 2, 2, 1, 3, 8, 15, 1, 5, 1, 3, 2, 9, 6, 14, 12, 8, 5, 5, 6, 16, 14, 1, 3, 6, 6, 2, 15, 8, 1, 2, 7, 9, 8, 16, 7, 3, 5, 3, 1, 3, 3, 1, 8, 14, 2, 8, 1, 5, 8, 3, 9, 1, 4, 1, 2, 4, 9, 4, 1, 4, 1, 12, 1, 5, 1, 2, 9, 3, 5, 7, 9, 9, 1, 5, 1, 1, 1, 7, 9, 12, 3, 1, 9, 4, 15, 2, 5, 1, 7, 5, 3, 1, 6, 4, 12, 4, 2, 5, 9, 8, 6, 1, 6, 1, 1, 12, 7, 4, 4, 12, 5, 1, 1, 15, 2, 3, 15, 7, 1, 6, 1, 2, 4, 5, 12, 5, 3, 1, 4, 14, 7, 10, 14, 8, 14, 1, 1, 5, 4, 1, 1, 9, 6, 2, 4, 7, 14, 4, 3, 7, 9, 2, 7, 16, 3, 6, 1, 16, 4, 1, 7, 3, 2, 12, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 2, 7, 1, 1, 1, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 1, 8, 8, 1, 16, 1, 2, 3]

In [ ]:
clusters = clusters_16[:]
surveys = pd.read_csv("emory_and_sinai_n675.csv")#.astype(str)
surveys["cluster"] = clusters
print(surveys["sex"].value_counts())
surveys

In [ ]:
covariate = "sex"
keys = list(np.unique(surveys[covariate].astype(str)))
temp = surveys[[covariate]]
temp["cluster"] = clusters
df = pd.DataFrame()
for cluster in np.unique(temp["cluster"]): 
    subset = temp[temp["cluster"] == cluster]
    dictionary = dict(subset.value_counts(covariate))
    key1 = keys[0]
    key2 = keys[1]
    key3 = "nan"
    dict_df = {"cluster": cluster, key1: 0, key2: 0, key3:0}
    if len(dictionary) == 2: 
        dict_df[key1] = dictionary[key1]
        dict_df[key2] = dictionary[key2]
    elif key1 in dictionary: 
        dict_df[key1] = dictionary[key1]
    elif key2 in dictionary: 
        dict_df[key2] = dictionary[key2]
    else: 
        dict_df[key3] = dict(subset.isna()[covariate].value_counts())[True]
    if sum(dictionary.values()) != subset.shape[0]: 
        dict_df[key3] = dict(subset.isna()[covariate].value_counts())[True]
    df = pd.concat([df, pd.DataFrame(dict_df, index = [0])])
# df = df.apply(lambda x: round(x, 2))
if covariate == "sex": 
    df = df[["cluster", "F", "M", "nan"]]
    values_m = df["M"] / (df["M"] + df["F"] + df["nan"])
    values_f = df["F"] / (df["M"] + df["F"] + df["nan"])
    values_nan = df["nan"] / (df["M"] + df["F"] + df["nan"])
    df["M"] = values_m
    df["F"] = values_f
    df["nan"] = values_nan
else: 
    df = df[["cluster", 1, 0, "nan"]]
if df["nan"].sum() == 0: del df["nan"]
df

In [ ]:
columns = ["C" + str(val) for val in df["cluster"]]
dictionary = dict(df.iloc[:,1:])

fig, ax = plt.subplots(layout='constrained', figsize = (8, 6))
x = np.arange(len(columns)) 
width = 0.6
multiplier = 0
bottom = np.zeros(df.shape[0])
colors = [sns.color_palette("Reds")[2:3], sns.color_palette("Blues")[2:3], "#d3d3d3"]

for attribute, measurement in dictionary.items(): 
    measurement = [round(val, 3) for val in measurement]
    if covariate == "bmi_cat_binary": 
        if attribute == 0: attribute = '<25, 25_to_30'
        elif attribute == 1: attribute = ">_30"
    elif covariate == "calcage_binary": 
        if attribute == 0: attribute = "<=50"
        elif attribute == 1: attribute = ">50"
    elif covariate == "income_binary": 
        if attribute == 0: attribute = "<=$100k"
        elif attribute == 1: attribute = ">$100k"
    elif "_binary" not in covariate: 
        if attribute == 0: attribute = "no " + covariate
        elif attribute == 1: attribute = covariate
    print(attribute, list(measurement))
    rects = ax.bar(x, measurement, width, label=attribute, bottom = bottom, color = colors[int(multiplier%3)])
    ax.bar_label(rects, label_type = "center", rotation = 0)
    multiplier += 1
    bottom += measurement

if covariate == "sex": 
    ax.plot([-0.5, 15.5], [0.5, 0.5], color = "grey")
    ax.set_ylabel('Percentage')
    ax.set_title('Percentage of ' + covariate + ' in each cluster')
else: 
    if covariate not in ["bmi_cat_binary", "income_binary", "calcage_binary", "smk", "student"]: 
        ax.set_ylim(0, 65)
    ax.set_ylabel('Number of patients')
    ax.set_title('Number of ' + covariate + ' in each cluster')
ax.set_xlabel("Cluster")
ax.legend(loc='upper left', ncols=1)
ax.set_xticks(x, columns, rotation = 0)
plt.show()

In [ ]:
conditions = merged.copy()
conditions["cluster"] = ["C" + str(c) for c in clusters_16]
dictionary = dict(conditions["cluster"].value_counts())
df = pd.DataFrame({"cluster": dictionary.keys(), "total": dictionary.values()})
df = df.sort_values(["total", "cluster"], ascending = [False, True])
for condition in comorb_dict.keys(): 
    patients = list(conditions[conditions[condition] == 1.0].index)
    dictionary = dict(conditions.iloc[patients, :]["cluster"].value_counts())
    df2 = pd.DataFrame({"cluster": list(dictionary.keys()), comorb_dict[condition]: list(dictionary.values())})
    df = df.merge(df2, on = "cluster", how = "outer")
    df["proportion_" + comorb_dict[condition]] = df[comorb_dict[condition]] / df["total"]
# df.to_csv("comorb_proportions_emory_sinai_15clusters.csv", index = False)
# df.to_csv("comorb_proportions_emory_sinai_16clusters.csv", index = False)
df

In [ ]:
conditions = merged.copy()
conditions["cluster"] = ["C" + str(c) for c in clusters]
dictionary = dict(conditions["cluster"].value_counts())
df = pd.DataFrame({"cluster": dictionary.keys(), "total": dictionary.values()})
df = df.sort_values(["total", "cluster"], ascending = [False, True])
for condition in comorb_dict.keys(): 
    patients = list(conditions[conditions[condition] == 1.0].index)
    dictionary = dict(conditions.iloc[patients, :]["cluster"].value_counts())
    df2 = pd.DataFrame({"cluster": list(dictionary.keys()), comorb_dict[condition]: list(dictionary.values())})
    df = df.merge(df2, on = "cluster", how = "outer")
    df["proportion_" + comorb_dict[condition]] = df[comorb_dict[condition]] / df["total"]
# df.to_csv("comorb_proportions_sinai.csv", index = False)
df

In [ ]:
# merged.to_csv("data_cleaned/emory_and_sinai_n885.csv", index = False)

# serum and mensa analysis

In [ ]:
print(data.shape)
cluster_dict = {3633: 4, 7191: 3, 7283: 7, 7385: 9, 7415: 2, 7423: 7, 7424: 16, 7426: 3, 7010: 6, 7023: 1, 7024: 16, 7030: 4, 7033: 1, 7034: 7, 7032: 3, 7053: 2, 7069: 12, 7075: 1, 7076: 1, 7077: 7, 7090: 1, 3198: 1, 3199: 1, 3231: 1, 3232: 1, 3234: 1, 3260: 1, 3264: 1, 3290: 5, 3292: 1, 3299: 1, 3320: 1, 3322: 1, 3323: 1, 3324: 1, 3339: 1, 3341: 2, 3346: 7, 3362: 1, 3365: 1, 3381: 1, 3386: 1, 3391: 1, 3400: 1, 3401: 1, 3404: 1, 3427: 7, 3438: 1, 3459: 1, 3460: 1, 3471: 1, 3474: 1, 3475: 1, 3503: 8, 3532: 8, 3556: 1, 3582: 16, 3580: 1, 3591: 2, 3593: 3}
data["cluster"] = [cluster_dict[int(val)] for val in data["record_id"]]
data

In [ ]:
cluster_severity = {"mild": [1], "moderate": [5, 4, 10, 11, 6, 8, 3, 13, 16], "severe": [2, 7, 12, 9, 15, 14]}
for key in list(cluster_severity.keys()): 
    for val in cluster_severity[key]: cluster_severity[val] = key
    del cluster_severity[key]
data["severity"] = [cluster_severity[int(val)] for val in data["cluster"]]
data["severity"].value_counts()

In [ ]:
import math
columns = ["record_id", "cluster", "severity"]
columns.extend(igg_cols)
df_igg = data[columns].copy()
df_igg = df_igg.set_index(["record_id", "cluster", "severity"])
df_igg = df_igg.astype(float)
df_igg = df_igg - df_igg.min() + 1
for col in df_igg.columns: 
    df_igg[col] = [math.log2(v) for v in df_igg[col]]
df_igg = df_igg.reset_index()
df_igg

In [ ]:
# Calculating mensa/serum mean values per cluster
df = pd.DataFrame()
df["sum"] = [2.693430126565952, 15.267783388134077, 13.622444758818038, 9.349821437001479, 7.531502417733883, 11.455694586117241, 16.085832351121763, 13.575811994776776, 23.02057402795433, 10.143111441440476, 11.0002448479398, 21.085280348374372, 14.941260304234193, 31.910781562092247, 28.21574051988618, 15.158387731989784]
df.index = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16']
df["cluster"] = [int(val.replace("C", "")) for val in df.index]

for col in df_igg.columns: 
    if "mensa" not in col and "serum" not in col: 
        continue
    values = {}
    for cluster in np.unique(df_igg["cluster"]): 
        subset = df_igg[df_igg["cluster"] == cluster]
        values[cluster] = subset[col].mean()
#     print(values)
    df["mean_" + col] = [values[c] if c in values else float('nan') for c in df['cluster']]
# df.to_csv("severity_sum_mean_mensa_serum.csv", index = False)
df

In [ ]:
import statannot
import seaborn as sns
import scipy.stats as stats
columns = list(filter(re.compile(".*_mensa_.*").match, df_igg.columns))
# columns = list(filter(re.compile(".*_serum_.*").match, df_igg.columns))
df = df_igg.melt(id_vars = ["record_id", "cluster", "severity"])
df = df[df["variable"].isin(columns)]
# df = df.replace("moderate", "severe")
df = df.rename(columns = {"variable": " ", "value": "log2-transformed values"})
df

In [ ]:
fig, (ax1) = plt.subplots(1, 1, figsize=(10, 5))
ax = sns.boxplot(df, x = " ", y = "log2-transformed values", hue = "severity", 
                 palette = {"mild": "green", "moderate": "yellow", "severe": "red"}, 
#                  hue_order = ["mild", "severe"], 
                 hue_order = ["mild", "moderate", "severe"], 
                )
a = plt.xticks(rotation = 80)
sns.move_legend(ax, "upper left", bbox_to_anchor = (1, 1))
box_pairs = []
p_values = []
pvalue_thresholds = []
# for var in np.unique(df[" "]): 
#     box_pairs.append(((var, "mild"), (var, "moderate")))
#     box_pairs.append(((var, "moderate"), (var, "severe")))
#     box_pairs.append(((var, "severe"), (var, "mild")))
for var in np.unique(df[" "]): 
    box_pairs.append(((var, "mild"), (var, "severe")))
    subset = df[df[" "] == var]
    s_1 = subset[subset["severity"] == "mild"]["log2-transformed values"]
    s_2 = subset[subset["severity"] == "moderate"]["log2-transformed values"]
    s_3 = subset[subset["severity"] == "severe"]["log2-transformed values"]
    f_statistic, p_value = stats.f_oneway(s_1, s_2, s_3)
    p_values.append(p_value)
    print(var, p_value)
    print(f_statistic)
#     pvalue_thresholds.append([p_value, round(p_value, 6)])
#     print(p_value)
# pvalue_thresholds.append([6.500e-03, "**"])
pvalue_thresholds = [[1e-4, "****"], [1e-3, "***"], [1e-2, "**"], [0.05, "*"], [1, "ns"]]
# pvalue_thresholds = [[0.55, "*"], [1, "ns"]]
# pvalue_thresholds = [[0.27, "*"], [1, "ns"]]
test_results = statannot.add_stat_annotation(ax, data = df, x = " ", y = "log2-transformed values", 
                                             perform_stat_test = False, pvalues = p_values, #test_short_name = "ANOVA test", 
                                             hue = "severity", 
#                                              hue_order = ["mild", "severe"], 
                                             hue_order = ["mild", "moderate", "severe"], 
                                             box_pairs = box_pairs, #test = 't-test_ind', 
                                             pvalue_thresholds = pvalue_thresholds, 
                                             text_format = 'star', loc = 'outside', verbose = 2)

Yes we need to do the correction. But for ANOVA, maybe we can use Tukey HSD.  Bonferroni may kill all significance - I don't know...

Also, double check the ANOVA and make sure the outputs are correct, which should include F values and degrees of freedom (within-group and between-group) before outputting p values.
 
make sure you use OLS when running ANOVA because our severity groups are ordered.
 
Based on the box plots, reviewers may ask us to do Kruskal-Wallis test instead of ANOVA because the data is a little skewed (especially the serum values) with outliers. ANOVA assume a Gaussian distribution.